<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Model;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Account extends \Application\Model\Account implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getAccountGroup()
    {
        $this->__load();
        return parent::getAccountGroup();
    }

    public function setAccountGroup(\Application\Model\AccountGroup $group = NULL)
    {
        $this->__load();
        return parent::setAccountGroup($group);
    }

    public function getAccountType()
    {
        $this->__load();
        return parent::getAccountType();
    }

    public function setAccountType($accountType = NULL)
    {
        $this->__load();
        return parent::setAccountType($accountType);
    }

    public function getBusinessUnit()
    {
        $this->__load();
        return parent::getBusinessUnit();
    }

    public function setBusinessUnit(\Application\Model\BusinessUnit $businessUnit = NULL)
    {
        $this->__load();
        return parent::setBusinessUnit($businessUnit);
    }

    public function getCategory()
    {
        $this->__load();
        return parent::getCategory();
    }

    public function setCategory($category)
    {
        $this->__load();
        return parent::setCategory($category);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getDoNotCall()
    {
        $this->__load();
        return parent::getDoNotCall();
    }

    public function setDoNotCall($do_not_call)
    {
        $this->__load();
        return parent::setDoNotCall($do_not_call);
    }

    public function getDoNotMail()
    {
        $this->__load();
        return parent::getDoNotMail();
    }

    public function setDoNotMail($do_not_mail)
    {
        $this->__load();
        return parent::setDoNotMail($do_not_mail);
    }

    public function getDoNotEmail()
    {
        $this->__load();
        return parent::getDoNotEmail();
    }

    public function setDoNotEmail($do_not_email)
    {
        $this->__load();
        return parent::setDoNotEmail($do_not_email);
    }

    public function getEmail1()
    {
        $this->__load();
        return parent::getEmail1();
    }

    public function setEmail1($email1)
    {
        $this->__load();
        return parent::setEmail1($email1);
    }

    public function getEmail2()
    {
        $this->__load();
        return parent::getEmail2();
    }

    public function setEmail2($email2)
    {
        $this->__load();
        return parent::setEmail2($email2);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getNote()
    {
        $this->__load();
        return parent::getNote();
    }

    public function setNote($note)
    {
        $this->__load();
        return parent::setNote($note);
    }

    public function getOriginatingLead()
    {
        $this->__load();
        return parent::getOriginatingLead();
    }

    public function setOriginatingLead(\Application\Model\Lead $lead = NULL)
    {
        $this->__load();
        return parent::setOriginatingLead($lead);
    }

    public function getOwner()
    {
        $this->__load();
        return parent::getOwner();
    }

    public function setOwner(\Application\Model\User $user = NULL)
    {
        $this->__load();
        return parent::setOwner($user);
    }

    public function getParentAccount()
    {
        $this->__load();
        return parent::getParentAccount();
    }

    public function setParentAccount(\Application\Model\Account $parentAccount = NULL)
    {
        $this->__load();
        return parent::setParentAccount($parentAccount);
    }

    public function getPrimaryContact()
    {
        $this->__load();
        return parent::getPrimaryContact();
    }

    public function setPrimaryContact(\Application\Model\Contact $primaryContact = NULL)
    {
        $this->__load();
        return parent::setPrimaryContact($primaryContact);
    }

    public function getReferrer()
    {
        $this->__load();
        return parent::getReferrer();
    }

    public function setReferrer(\Application\Model\Account $referrer = NULL)
    {
        $this->__load();
        return parent::setReferrer($referrer);
    }

    public function getSource()
    {
        $this->__load();
        return parent::getSource();
    }

    public function setSource($source = NULL)
    {
        $this->__load();
        return parent::setSource($source);
    }

    public function getState()
    {
        $this->__load();
        return parent::getState();
    }

    public function setState($state = NULL)
    {
        $this->__load();
        return parent::setState($state);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setStatus($status = NULL)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getWebsite()
    {
        $this->__load();
        return parent::getWebsite();
    }

    public function setWebsite($website)
    {
        $this->__load();
        return parent::setWebsite($website);
    }

    public function getCreationDate()
    {
        $this->__load();
        return parent::getCreationDate();
    }

    public function setCreationDate($creationDate)
    {
        $this->__load();
        return parent::setCreationDate($creationDate);
    }

    public function getLastUpdateDate()
    {
        $this->__load();
        return parent::getLastUpdateDate();
    }

    public function setLastUpdateDate($lastUpdateDate)
    {
        $this->__load();
        return parent::setLastUpdateDate($lastUpdateDate);
    }

    public function getAddresses()
    {
        $this->__load();
        return parent::getAddresses();
    }

    public function setAddresses(\Doctrine\Common\Collections\ArrayCollection $addresses)
    {
        $this->__load();
        return parent::setAddresses($addresses);
    }

    public function addAddresses(\Doctrine\Common\Collections\ArrayCollection $addresses)
    {
        $this->__load();
        return parent::addAddresses($addresses);
    }

    public function removeAddresses(\Doctrine\Common\Collections\ArrayCollection $addresses)
    {
        $this->__load();
        return parent::removeAddresses($addresses);
    }

    public function addAddress(\Application\Model\Address $address)
    {
        $this->__load();
        return parent::addAddress($address);
    }

    public function removeAddress(\Application\Model\Address $address)
    {
        $this->__load();
        return parent::removeAddress($address);
    }

    public function getAppointments()
    {
        $this->__load();
        return parent::getAppointments();
    }

    public function setAppointments(\Doctrine\Common\Collections\ArrayCollection $appointments)
    {
        $this->__load();
        return parent::setAppointments($appointments);
    }

    public function getChildAccounts()
    {
        $this->__load();
        return parent::getChildAccounts();
    }

    public function setChildAccounts(\Doctrine\Common\Collections\ArrayCollection $childAccounts)
    {
        $this->__load();
        return parent::setChildAccounts($childAccounts);
    }

    public function addChildAccount(\Application\Model\Account $childAccount)
    {
        $this->__load();
        return parent::addChildAccount($childAccount);
    }

    public function removeChildAccount(\Application\Model\Account $childAccount)
    {
        $this->__load();
        return parent::removeChildAccount($childAccount);
    }

    public function getAuditItems()
    {
        $this->__load();
        return parent::getAuditItems();
    }

    public function setAuditItems(\Doctrine\Common\Collections\ArrayCollection $auditItems)
    {
        $this->__load();
        return parent::setAuditItems($auditItems);
    }

    public function addAuditItem(\Application\Model\Audit $auditItem)
    {
        $this->__load();
        return parent::addAuditItem($auditItem);
    }

    public function removeAuditItem(\Application\Model\Audit $auditItem)
    {
        $this->__load();
        return parent::removeAuditItem($auditItem);
    }

    public function getContacts()
    {
        $this->__load();
        return parent::getContacts();
    }

    public function setContacts(\Doctrine\Common\Collections\ArrayCollection $contacts)
    {
        $this->__load();
        return parent::setContacts($contacts);
    }

    public function addContact(\Application\Model\Contact $contact)
    {
        $this->__load();
        return parent::addContact($contact);
    }

    public function removeContact(\Application\Model\Contact $contact)
    {
        $this->__load();
        return parent::removeContact($contact);
    }

    public function getInteractions()
    {
        $this->__load();
        return parent::getInteractions();
    }

    public function setInteractions(\Doctrine\Common\Collections\ArrayCollection $interactions)
    {
        $this->__load();
        return parent::setInteractions($interactions);
    }

    public function getLeads()
    {
        $this->__load();
        return parent::getLeads();
    }

    public function setLeads(\Doctrine\Common\Collections\ArrayCollection $leads)
    {
        $this->__load();
        return parent::setLeads($leads);
    }

    public function addLead(\Application\Model\Lead $lead)
    {
        $this->__load();
        return parent::addLead($lead);
    }

    public function removeLead(\Application\Model\Lead $lead)
    {
        $this->__load();
        return parent::removeLead($lead);
    }

    public function getNotes()
    {
        $this->__load();
        return parent::getNotes();
    }

    public function setNotes(\Doctrine\Common\Collections\ArrayCollection $notes)
    {
        $this->__load();
        return parent::setNotes($notes);
    }

    public function addNote(\Application\Model\AbstractNote $note)
    {
        $this->__load();
        return parent::addNote($note);
    }

    public function removeNote(\Application\Model\AbstractNote $note)
    {
        $this->__load();
        return parent::removeNote($note);
    }

    public function getOpportunities()
    {
        $this->__load();
        return parent::getOpportunities();
    }

    public function setOpportunities(\Doctrine\Common\Collections\ArrayCollection $opportunities)
    {
        $this->__load();
        return parent::setOpportunities($opportunities);
    }

    public function addOpportunity(\Application\Model\Opportunity $opportunity)
    {
        $this->__load();
        return parent::addOpportunity($opportunity);
    }

    public function removeOpportunity(\Application\Model\Opportunity $opportunity)
    {
        $this->__load();
        return parent::removeOpportunity($opportunity);
    }

    public function getReferrals()
    {
        $this->__load();
        return parent::getReferrals();
    }

    public function setReferrals(\Doctrine\Common\Collections\ArrayCollection $referrals)
    {
        $this->__load();
        return parent::setReferrals($referrals);
    }

    public function addReferral(\Application\Model\Account $referral)
    {
        $this->__load();
        return parent::addReferral($referral);
    }

    public function removeReferral(\Application\Model\Account $referral)
    {
        $this->__load();
        return parent::removeReferral($referral);
    }

    public function getTasks()
    {
        $this->__load();
        return parent::getTasks();
    }

    public function setTasks(\Doctrine\Common\Collections\ArrayCollection $tasks)
    {
        $this->__load();
        return parent::setTasks($tasks);
    }

    public function addTask(\Application\Model\AbstractTask $task)
    {
        $this->__load();
        return parent::addTask($task);
    }

    public function removeTask(\Application\Model\AbstractTask $task)
    {
        $this->__load();
        return parent::removeTask($task);
    }

    public function getTelephones()
    {
        $this->__load();
        return parent::getTelephones();
    }

    public function setTelephones(\Doctrine\Common\Collections\ArrayCollection $telephones)
    {
        $this->__load();
        return parent::setTelephones($telephones);
    }

    public function addTelephones(\Doctrine\Common\Collections\ArrayCollection $telephones)
    {
        $this->__load();
        return parent::addTelephones($telephones);
    }

    public function removeTelephones(\Doctrine\Common\Collections\ArrayCollection $telephones)
    {
        $this->__load();
        return parent::removeTelephones($telephones);
    }

    public function addTelephone(\Application\Model\Telephone $telephone)
    {
        $this->__load();
        return parent::addTelephone($telephone);
    }

    public function removeTelephone(\Application\Model\Telephone $telephone)
    {
        $this->__load();
        return parent::removeTelephone($telephone);
    }

    public function addActivities(\Doctrine\Common\Collections\ArrayCollection $activities)
    {
        $this->__load();
        return parent::addActivities($activities);
    }

    public function removeActivities(\Doctrine\Common\Collections\ArrayCollection $activities)
    {
        $this->__load();
        return parent::removeActivities($activities);
    }

    public function addActivity(\Application\Model\AbstractActivity $activity)
    {
        $this->__load();
        return parent::addActivity($activity);
    }

    public function removeActivity(\Application\Model\AbstractActivity $activity)
    {
        $this->__load();
        return parent::removeActivity($activity);
    }

    public function getLists()
    {
        $this->__load();
        return parent::getLists();
    }

    public function setLists(\Doctrine\Common\Collections\ArrayCollection $lists)
    {
        $this->__load();
        return parent::setLists($lists);
    }

    public function addList(\Application\Model\MarketingList $list)
    {
        $this->__load();
        return parent::addList($list);
    }

    public function removeList(\Application\Model\MarketingList $list)
    {
        $this->__load();
        return parent::removeList($list);
    }

    public function equals(\Application\Stdlib\Object $o)
    {
        $this->__load();
        return parent::equals($o);
    }

    public function getAuditableProperties()
    {
        $this->__load();
        return parent::getAuditableProperties();
    }

    public function getClass()
    {
        $this->__load();
        return parent::getClass();
    }

    public function getDisplayName($includeLink = false)
    {
        $this->__load();
        return parent::getDisplayName($includeLink);
    }

    public function getOpenActivities()
    {
        $this->__load();
        return parent::getOpenActivities();
    }

    public function getClosedActivities()
    {
        $this->__load();
        return parent::getClosedActivities();
    }

    public function getPrimaryAddress()
    {
        $this->__load();
        return parent::getPrimaryAddress();
    }

    public function getPrimaryTelephone()
    {
        $this->__load();
        return parent::getPrimaryTelephone();
    }

    public function getSmtpEmailAddress()
    {
        $this->__load();
        return parent::getSmtpEmailAddress();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function importPrimaryContactInformation()
    {
        $this->__load();
        return parent::importPrimaryContactInformation();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'accountType', 'category', 'description', 'doNotCall', 'doNotMail', 'doNotEmail', 'email1', 'email2', 'name', 'note', 'source', 'state', 'status', 'website', 'creationDate', 'lastUpdateDate', 'accountGroup', 'businessUnit', 'originatingLead', 'owner', 'parentAccount', 'primaryContact', 'referrer', 'addresses', 'appointments', 'auditItems', 'childAccounts', 'contacts', 'interactions', 'leads', 'notes', 'opportunities', 'referrals', 'tasks', 'telephones', 'lists');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}