<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Model;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class BulkOperation extends \Application\Model\BulkOperation implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setActualEnd($actualEnd = NULL, $bypassFilter = false)
    {
        $this->__load();
        return parent::setActualEnd($actualEnd, $bypassFilter);
    }

    public function setActualStart($actualStart = NULL, $bypassFilter = false)
    {
        $this->__load();
        return parent::setActualStart($actualStart, $bypassFilter);
    }

    public function getCreatedRecordType()
    {
        $this->__load();
        return parent::getCreatedRecordType();
    }

    public function setCreatedRecordType($createdRecordType = NULL)
    {
        $this->__load();
        return parent::setCreatedRecordType($createdRecordType);
    }

    public function getDiscriminator()
    {
        $this->__load();
        return parent::getDiscriminator();
    }

    public function getFailureCount()
    {
        $this->__load();
        return parent::getFailureCount();
    }

    public function setFailureCount($failureCount)
    {
        $this->__load();
        return parent::setFailureCount($failureCount);
    }

    public function getMarketingList()
    {
        $this->__load();
        return parent::getMarketingList();
    }

    public function setMarketingList(\Application\Model\MarketingList $list = NULL)
    {
        $this->__load();
        return parent::setMarketingList($list);
    }

    public function getOperationType()
    {
        $this->__load();
        return parent::getOperationType();
    }

    public function setOperationType($operationType = NULL)
    {
        $this->__load();
        return parent::setOperationType($operationType);
    }

    public function getParameters()
    {
        $this->__load();
        return parent::getParameters();
    }

    public function setParameters($parameters)
    {
        $this->__load();
        return parent::setParameters($parameters);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setStatus($status = NULL)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getSuccessCount()
    {
        $this->__load();
        return parent::getSuccessCount();
    }

    public function setSuccessCount($successCount)
    {
        $this->__load();
        return parent::setSuccessCount($successCount);
    }

    public function getTargetedRecordType()
    {
        $this->__load();
        return parent::getTargetedRecordType();
    }

    public function setTargetedRecordType($targetedRecordType = NULL)
    {
        $this->__load();
        return parent::setTargetedRecordType($targetedRecordType);
    }

    public function getTargetMembersCount()
    {
        $this->__load();
        return parent::getTargetMembersCount();
    }

    public function setTargetMembersCount($targetMembersCount)
    {
        $this->__load();
        return parent::setTargetMembersCount($targetMembersCount);
    }

    public function getBulkInteractions()
    {
        $this->__load();
        return parent::getBulkInteractions();
    }

    public function setBulkInteractions(\Doctrine\Common\Collections\ArrayCollection $bulkInteractions)
    {
        $this->__load();
        return parent::setBulkInteractions($bulkInteractions);
    }

    public function addBulkInteraction(\Application\Model\AbstractInteraction $interaction)
    {
        $this->__load();
        return parent::addBulkInteraction($interaction);
    }

    public function removeBulkInteraction(\Application\Model\AbstractInteraction $interaction)
    {
        $this->__load();
        return parent::removeBulkInteraction($interaction);
    }

    public function getActualStart()
    {
        $this->__load();
        return parent::getActualStart();
    }

    public function getActualEnd()
    {
        $this->__load();
        return parent::getActualEnd();
    }

    public function equals(\Application\Stdlib\Object $o)
    {
        $this->__load();
        return parent::equals($o);
    }

    public function getFormattedActualEnd($format = NULL)
    {
        $this->__load();
        return parent::getFormattedActualEnd($format);
    }

    public function getFormattedActualStart($format = NULL)
    {
        $this->__load();
        return parent::getFormattedActualStart($format);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getScheduledStart()
    {
        $this->__load();
        return parent::getScheduledStart();
    }

    public function setScheduledStart($scheduledStart)
    {
        $this->__load();
        return parent::setScheduledStart($scheduledStart);
    }

    public function getScheduledEnd()
    {
        $this->__load();
        return parent::getScheduledEnd();
    }

    public function setScheduledEnd($scheduledEnd)
    {
        $this->__load();
        return parent::setScheduledEnd($scheduledEnd);
    }

    public function getFormattedScheduledEnd($format = NULL)
    {
        $this->__load();
        return parent::getFormattedScheduledEnd($format);
    }

    public function getFormattedScheduledStart($format = NULL)
    {
        $this->__load();
        return parent::getFormattedScheduledStart($format);
    }

    public function getPriority()
    {
        $this->__load();
        return parent::getPriority();
    }

    public function setPriority($priority = NULL)
    {
        $this->__load();
        return parent::setPriority($priority);
    }

    public function getState()
    {
        $this->__load();
        return parent::getState();
    }

    public function setState($state = NULL)
    {
        $this->__load();
        return parent::setState($state);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setDiscriminator($discriminator)
    {
        $this->__load();
        return parent::setDiscriminator($discriminator);
    }

    public function getAccount()
    {
        $this->__load();
        return parent::getAccount();
    }

    public function setAccount(\Application\Model\Account $account = NULL)
    {
        $this->__load();
        return parent::setAccount($account);
    }

    public function getBusinessUnit()
    {
        $this->__load();
        return parent::getBusinessUnit();
    }

    public function setBusinessUnit(\Application\Model\BusinessUnit $businessUnit = NULL)
    {
        $this->__load();
        return parent::setBusinessUnit($businessUnit);
    }

    public function getCampaign()
    {
        $this->__load();
        return parent::getCampaign();
    }

    public function setCampaign(\Application\Model\Campaign $campaign = NULL)
    {
        $this->__load();
        return parent::setCampaign($campaign);
    }

    public function getCampaignActivity()
    {
        $this->__load();
        return parent::getCampaignActivity();
    }

    public function setCampaignActivity(\Application\Model\CampaignActivity $campaignActivity = NULL)
    {
        $this->__load();
        return parent::setCampaignActivity($campaignActivity);
    }

    public function getContact()
    {
        $this->__load();
        return parent::getContact();
    }

    public function setContact(\Application\Model\Contact $contact = NULL)
    {
        $this->__load();
        return parent::setContact($contact);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getLead()
    {
        $this->__load();
        return parent::getLead();
    }

    public function setLead(\Application\Model\Lead $lead = NULL)
    {
        $this->__load();
        return parent::setLead($lead);
    }

    public function getLongNotes()
    {
        $this->__load();
        return parent::getLongNotes();
    }

    public function setLongNotes($longNotes)
    {
        $this->__load();
        return parent::setLongNotes($longNotes);
    }

    public function getNotes()
    {
        $this->__load();
        return parent::getNotes();
    }

    public function setNotes($notes)
    {
        $this->__load();
        return parent::setNotes($notes);
    }

    public function getOpportunity()
    {
        $this->__load();
        return parent::getOpportunity();
    }

    public function setOpportunity(\Application\Model\Opportunity $opportunity = NULL)
    {
        $this->__load();
        return parent::setOpportunity($opportunity);
    }

    public function getOwner()
    {
        $this->__load();
        return parent::getOwner();
    }

    public function setOwner(\Application\Model\User $user = NULL)
    {
        $this->__load();
        return parent::setOwner($user);
    }

    public function getSubject()
    {
        $this->__load();
        return parent::getSubject();
    }

    public function setSubject($subject)
    {
        $this->__load();
        return parent::setSubject($subject);
    }

    public function getCreationDate()
    {
        $this->__load();
        return parent::getCreationDate();
    }

    public function setCreationDate($creationDate)
    {
        $this->__load();
        return parent::setCreationDate($creationDate);
    }

    public function getLastUpdateDate()
    {
        $this->__load();
        return parent::getLastUpdateDate();
    }

    public function setLastUpdateDate($lastUpdateDate)
    {
        $this->__load();
        return parent::setLastUpdateDate($lastUpdateDate);
    }

    public function getAuditItems()
    {
        $this->__load();
        return parent::getAuditItems();
    }

    public function setAuditItems(\Doctrine\Common\Collections\ArrayCollection $auditItems)
    {
        $this->__load();
        return parent::setAuditItems($auditItems);
    }

    public function addAuditItem(\Application\Model\Audit $auditItem)
    {
        $this->__load();
        return parent::addAuditItem($auditItem);
    }

    public function removeAuditItem(\Application\Model\Audit $auditItem)
    {
        $this->__load();
        return parent::removeAuditItem($auditItem);
    }

    public function getAuditableProperties()
    {
        $this->__load();
        return parent::getAuditableProperties();
    }

    public function getClass()
    {
        $this->__load();
        return parent::getClass();
    }

    public function getDescriptionLink($id = NULL, $route = NULL)
    {
        $this->__load();
        return parent::getDescriptionLink($id, $route);
    }

    public function getDiscriminatorTitle()
    {
        $this->__load();
        return parent::getDiscriminatorTitle();
    }

    public function getListTitle()
    {
        $this->__load();
        return parent::getListTitle();
    }

    public function getRegardingObject()
    {
        $this->__load();
        return parent::getRegardingObject();
    }

    public function getRegardingObjectName($includeLink = false)
    {
        $this->__load();
        return parent::getRegardingObjectName($includeLink);
    }

    public function getTopic()
    {
        $this->__load();
        return parent::getTopic();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'description', 'longNotes', 'notes', 'subject', 'creationDate', 'lastUpdateDate', 'account', 'businessUnit', 'campaign', 'campaignActivity', 'contact', 'lead', 'opportunity', 'owner', 'auditItems', 'priority', 'state', 'status', 'scheduledStart', 'scheduledEnd', 'actualStart', 'actualEnd', 'createdRecordType', 'failureCount', 'operationType', 'parameters', 'successCount', 'targetMembersCount', 'targetedRecordType', 'marketingList', 'bulkInteractions');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}