<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Model;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Contact extends \Application\Model\Contact implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getAccount()
    {
        $this->__load();
        return parent::getAccount();
    }

    public function setAccount(\Application\Model\Account $account = NULL)
    {
        $this->__load();
        return parent::setAccount($account);
    }

    public function getAssistantEmail()
    {
        $this->__load();
        return parent::getAssistantEmail();
    }

    public function setAssistantEmail($assistantEmail)
    {
        $this->__load();
        return parent::setAssistantEmail($assistantEmail);
    }

    public function getAssistantName()
    {
        $this->__load();
        return parent::getAssistantName();
    }

    public function setAssistantName($assistantName)
    {
        $this->__load();
        return parent::setAssistantName($assistantName);
    }

    public function getAssistantTelephone()
    {
        $this->__load();
        return parent::getAssistantTelephone();
    }

    public function setAssistantTelephone($assistantTelephone)
    {
        $this->__load();
        return parent::setAssistantTelephone($assistantTelephone);
    }

    public function getBirthDate()
    {
        $this->__load();
        return parent::getBirthDate();
    }

    public function setBirthDate($birthDate = NULL)
    {
        $this->__load();
        return parent::setBirthDate($birthDate);
    }

    public function getBusinessUnit()
    {
        $this->__load();
        return parent::getBusinessUnit();
    }

    public function setBusinessUnit(\Application\Model\BusinessUnit $businessUnit = NULL)
    {
        $this->__load();
        return parent::setBusinessUnit($businessUnit);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getDoNotCall()
    {
        $this->__load();
        return parent::getDoNotCall();
    }

    public function setDoNotCall($doNotCall)
    {
        $this->__load();
        return parent::setDoNotCall($doNotCall);
    }

    public function getDoNotEmail()
    {
        $this->__load();
        return parent::getDoNotEmail();
    }

    public function setDoNotEmail($doNotEmail)
    {
        $this->__load();
        return parent::setDoNotEmail($doNotEmail);
    }

    public function getDoNotMail()
    {
        $this->__load();
        return parent::getDoNotMail();
    }

    public function setDoNotMail($doNotMail)
    {
        $this->__load();
        return parent::setDoNotMail($doNotMail);
    }

    public function getEmail1()
    {
        $this->__load();
        return parent::getEmail1();
    }

    public function setEmail1($email1)
    {
        $this->__load();
        return parent::setEmail1($email1);
    }

    public function getEmail2()
    {
        $this->__load();
        return parent::getEmail2();
    }

    public function setEmail2($email2)
    {
        $this->__load();
        return parent::setEmail2($email2);
    }

    public function getFirstName()
    {
        $this->__load();
        return parent::getFirstName();
    }

    public function setFirstName($firstName)
    {
        $this->__load();
        return parent::setFirstName($firstName);
    }

    public function getDisplayName($includeLink = NULL)
    {
        $this->__load();
        return parent::getDisplayName($includeLink);
    }

    public function setDisplayName($displayName)
    {
        $this->__load();
        return parent::setDisplayName($displayName);
    }

    public function getGender()
    {
        $this->__load();
        return parent::getGender();
    }

    public function setGender($gender = NULL)
    {
        $this->__load();
        return parent::setGender($gender);
    }

    public function getInterests()
    {
        $this->__load();
        return parent::getInterests();
    }

    public function setInterests($interests)
    {
        $this->__load();
        return parent::setInterests($interests);
    }

    public function getIsPrimaryContact()
    {
        $this->__load();
        return parent::getIsPrimaryContact();
    }

    public function setIsPrimaryContact($isPrimaryContact)
    {
        $this->__load();
        return parent::setIsPrimaryContact($isPrimaryContact);
    }

    public function getJobTitle()
    {
        $this->__load();
        return parent::getJobTitle();
    }

    public function setJobTitle($jobTitle)
    {
        $this->__load();
        return parent::setJobTitle($jobTitle);
    }

    public function getLastName()
    {
        $this->__load();
        return parent::getLastName();
    }

    public function setLastName($lastName)
    {
        $this->__load();
        return parent::setLastName($lastName);
    }

    public function getMiddleName()
    {
        $this->__load();
        return parent::getMiddleName();
    }

    public function setMiddleName($middleName)
    {
        $this->__load();
        return parent::setMiddleName($middleName);
    }

    public function getNickname()
    {
        $this->__load();
        return parent::getNickname();
    }

    public function setNickname($nickname)
    {
        $this->__load();
        return parent::setNickname($nickname);
    }

    public function getOriginatingLead()
    {
        $this->__load();
        return parent::getOriginatingLead();
    }

    public function setOriginatingLead(\Application\Model\Lead $originatingLead = NULL)
    {
        $this->__load();
        return parent::setOriginatingLead($originatingLead);
    }

    public function getOwner()
    {
        $this->__load();
        return parent::getOwner();
    }

    public function setOwner(\Application\Model\User $user = NULL)
    {
        $this->__load();
        return parent::setOwner($user);
    }

    public function getPrefix()
    {
        $this->__load();
        return parent::getPrefix();
    }

    public function setPrefix($prefix)
    {
        $this->__load();
        return parent::setPrefix($prefix);
    }

    public function getSalutation()
    {
        $this->__load();
        return parent::getSalutation();
    }

    public function setSalutation($salutation)
    {
        $this->__load();
        return parent::setSalutation($salutation);
    }

    public function getSortName()
    {
        $this->__load();
        return parent::getSortName();
    }

    public function setSortName($sortName = NULL)
    {
        $this->__load();
        return parent::setSortName($sortName);
    }

    public function getState()
    {
        $this->__load();
        return parent::getState();
    }

    public function setState($state = NULL)
    {
        $this->__load();
        return parent::setState($state);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setStatus($status = NULL)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getSuffix()
    {
        $this->__load();
        return parent::getSuffix();
    }

    public function setSuffix($suffix)
    {
        $this->__load();
        return parent::setSuffix($suffix);
    }

    public function getWebsite()
    {
        $this->__load();
        return parent::getWebsite();
    }

    public function setWebsite($website)
    {
        $this->__load();
        return parent::setWebsite($website);
    }

    public function getCreationDate()
    {
        $this->__load();
        return parent::getCreationDate();
    }

    public function setCreationDate($creationDate)
    {
        $this->__load();
        return parent::setCreationDate($creationDate);
    }

    public function getLastUpdateDate()
    {
        $this->__load();
        return parent::getLastUpdateDate();
    }

    public function setLastUpdateDate($lastUpdateDate)
    {
        $this->__load();
        return parent::setLastUpdateDate($lastUpdateDate);
    }

    public function getAppointments()
    {
        $this->__load();
        return parent::getAppointments();
    }

    public function setAppointments(\Doctrine\Common\Collections\ArrayCollection $appointments)
    {
        $this->__load();
        return parent::setAppointments($appointments);
    }

    public function getAuditItems()
    {
        $this->__load();
        return parent::getAuditItems();
    }

    public function setAuditItems(\Doctrine\Common\Collections\ArrayCollection $auditItems)
    {
        $this->__load();
        return parent::setAuditItems($auditItems);
    }

    public function addAuditItem(\Application\Model\Audit $auditItem)
    {
        $this->__load();
        return parent::addAuditItem($auditItem);
    }

    public function removeAuditItem(\Application\Model\Audit $auditItem)
    {
        $this->__load();
        return parent::removeAuditItem($auditItem);
    }

    public function getInteractions()
    {
        $this->__load();
        return parent::getInteractions();
    }

    public function setInteractions(\Doctrine\Common\Collections\ArrayCollection $interactions)
    {
        $this->__load();
        return parent::setInteractions($interactions);
    }

    public function getNotes()
    {
        $this->__load();
        return parent::getNotes();
    }

    public function setNotes(\Doctrine\Common\Collections\ArrayCollection $notes)
    {
        $this->__load();
        return parent::setNotes($notes);
    }

    public function getTasks()
    {
        $this->__load();
        return parent::getTasks();
    }

    public function setTasks(\Doctrine\Common\Collections\ArrayCollection $tasks)
    {
        $this->__load();
        return parent::setTasks($tasks);
    }

    public function getLists()
    {
        $this->__load();
        return parent::getLists();
    }

    public function setLists(\Doctrine\Common\Collections\ArrayCollection $lists)
    {
        $this->__load();
        return parent::setLists($lists);
    }

    public function addActivities(\Doctrine\Common\Collections\ArrayCollection $activities)
    {
        $this->__load();
        return parent::addActivities($activities);
    }

    public function removeActivities(\Doctrine\Common\Collections\ArrayCollection $activities)
    {
        $this->__load();
        return parent::removeActivities($activities);
    }

    public function addActivity(\Application\Model\AbstractActivity $activity)
    {
        $this->__load();
        return parent::addActivity($activity);
    }

    public function removeActivity(\Application\Model\AbstractActivity $activity)
    {
        $this->__load();
        return parent::removeActivity($activity);
    }

    public function getAddresses()
    {
        $this->__load();
        return parent::getAddresses();
    }

    public function setAddresses(\Doctrine\Common\Collections\ArrayCollection $addresses)
    {
        $this->__load();
        return parent::setAddresses($addresses);
    }

    public function addAddresses(\Doctrine\Common\Collections\ArrayCollection $addresses)
    {
        $this->__load();
        return parent::addAddresses($addresses);
    }

    public function removeAddresses(\Doctrine\Common\Collections\ArrayCollection $addresses)
    {
        $this->__load();
        return parent::removeAddresses($addresses);
    }

    public function addAddress(\Application\Model\Address $address)
    {
        $this->__load();
        return parent::addAddress($address);
    }

    public function removeAddress(\Application\Model\Address $address)
    {
        $this->__load();
        return parent::removeAddress($address);
    }

    public function getTelephones()
    {
        $this->__load();
        return parent::getTelephones();
    }

    public function setTelephones(\Doctrine\Common\Collections\ArrayCollection $telephones)
    {
        $this->__load();
        return parent::setTelephones($telephones);
    }

    public function addTelephones(\Doctrine\Common\Collections\ArrayCollection $telephones)
    {
        $this->__load();
        return parent::addTelephones($telephones);
    }

    public function removeTelephones(\Doctrine\Common\Collections\ArrayCollection $telephones)
    {
        $this->__load();
        return parent::removeTelephones($telephones);
    }

    public function addTelephone(\Application\Model\Telephone $telephone)
    {
        $this->__load();
        return parent::addTelephone($telephone);
    }

    public function removeTelephone(\Application\Model\Telephone $telephone)
    {
        $this->__load();
        return parent::removeTelephone($telephone);
    }

    public function addList(\Application\Model\MarketingList $list)
    {
        $this->__load();
        return parent::addList($list);
    }

    public function removeList(\Application\Model\MarketingList $list)
    {
        $this->__load();
        return parent::removeList($list);
    }

    public function computeDisplayName()
    {
        $this->__load();
        return parent::computeDisplayName();
    }

    public function equals(\Application\Stdlib\Object $o)
    {
        $this->__load();
        return parent::equals($o);
    }

    public function getAccountLink()
    {
        $this->__load();
        return parent::getAccountLink();
    }

    public function getAuditableProperties()
    {
        $this->__load();
        return parent::getAuditableProperties();
    }

    public function getClass()
    {
        $this->__load();
        return parent::getClass();
    }

    public function getClosedActivities()
    {
        $this->__load();
        return parent::getClosedActivities();
    }

    public function getEmailLink()
    {
        $this->__load();
        return parent::getEmailLink();
    }

    public function getOpenActivities()
    {
        $this->__load();
        return parent::getOpenActivities();
    }

    public function getPrimaryAddress()
    {
        $this->__load();
        return parent::getPrimaryAddress();
    }

    public function getPrimaryTelephone()
    {
        $this->__load();
        return parent::getPrimaryTelephone();
    }

    public function getShortAccountName()
    {
        $this->__load();
        return parent::getShortAccountName();
    }

    public function getSmtpEmailAddress()
    {
        $this->__load();
        return parent::getSmtpEmailAddress();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'assistantEmail', 'assistantName', 'assistantTelephone', 'birthDate', 'description', 'doNotCall', 'doNotEmail', 'doNotMail', 'email1', 'email2', 'firstName', 'displayName', 'gender', 'interests', 'isPrimaryContact', 'jobTitle', 'lastName', 'middleName', 'nickname', 'prefix', 'salutation', 'sortName', 'state', 'status', 'suffix', 'website', 'creationDate', 'lastUpdateDate', 'account', 'businessUnit', 'originatingLead', 'owner', 'appointments', 'auditItems', 'interactions', 'notes', 'tasks', 'addresses', 'telephones', 'lists');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}