<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Model;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class BusinessUnit extends \Application\Model\BusinessUnit implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getCostCenter()
    {
        $this->__load();
        return parent::getCostCenter();
    }

    public function setCostCenter($costCenter)
    {
        $this->__load();
        return parent::setCostCenter($costCenter);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getDisabledReason()
    {
        $this->__load();
        return parent::getDisabledReason();
    }

    public function setDisabledReason($disabledReason)
    {
        $this->__load();
        return parent::setDisabledReason($disabledReason);
    }

    public function getDivisionName()
    {
        $this->__load();
        return parent::getDivisionName();
    }

    public function setDivisionName($divisionName)
    {
        $this->__load();
        return parent::setDivisionName($divisionName);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getIsDisabled()
    {
        $this->__load();
        return parent::getIsDisabled();
    }

    public function setIsDiabled($isDiabled)
    {
        $this->__load();
        return parent::setIsDiabled($isDiabled);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getOrganization()
    {
        $this->__load();
        return parent::getOrganization();
    }

    public function setOrganization(\Application\Model\Organization $organization = NULL)
    {
        $this->__load();
        return parent::setOrganization($organization);
    }

    public function getParentBusinessUnit()
    {
        $this->__load();
        return parent::getParentBusinessUnit();
    }

    public function setParentBusinessUnit(\Application\Model\BusinessUnit $parentBusinessUnit = NULL)
    {
        $this->__load();
        return parent::setParentBusinessUnit($parentBusinessUnit);
    }

    public function getWebsite()
    {
        $this->__load();
        return parent::getWebsite();
    }

    public function setWebsite($website)
    {
        $this->__load();
        return parent::setWebsite($website);
    }

    public function getCreationDate()
    {
        $this->__load();
        return parent::getCreationDate();
    }

    public function setCreationDate($creationDate)
    {
        $this->__load();
        return parent::setCreationDate($creationDate);
    }

    public function getLastUpdateDate()
    {
        $this->__load();
        return parent::getLastUpdateDate();
    }

    public function setLastUpdateDate($lastUpdateDate)
    {
        $this->__load();
        return parent::setLastUpdateDate($lastUpdateDate);
    }

    public function getAddresses()
    {
        $this->__load();
        return parent::getAddresses();
    }

    public function setAddresses(\Doctrine\Common\Collections\ArrayCollection $addresses)
    {
        $this->__load();
        return parent::setAddresses($addresses);
    }

    public function addAddress(\Application\Model\Address $address)
    {
        $this->__load();
        return parent::addAddress($address);
    }

    public function removeAddress(\Application\Model\Address $address)
    {
        $this->__load();
        return parent::removeAddress($address);
    }

    public function addAddresses(\Doctrine\Common\Collections\ArrayCollection $addresses)
    {
        $this->__load();
        return parent::addAddresses($addresses);
    }

    public function removeAddresses(\Doctrine\Common\Collections\ArrayCollection $addresses)
    {
        $this->__load();
        return parent::removeAddresses($addresses);
    }

    public function getAuditItems()
    {
        $this->__load();
        return parent::getAuditItems();
    }

    public function setAuditItems(\Doctrine\Common\Collections\ArrayCollection $auditItems)
    {
        $this->__load();
        return parent::setAuditItems($auditItems);
    }

    public function addAuditItem(\Application\Model\Audit $auditItem)
    {
        $this->__load();
        return parent::addAuditItem($auditItem);
    }

    public function removeAuditItem(\Application\Model\Audit $auditItem)
    {
        $this->__load();
        return parent::removeAuditItem($auditItem);
    }

    public function getChildren()
    {
        $this->__load();
        return parent::getChildren();
    }

    public function setChildren(\Doctrine\Common\Collections\ArrayCollection $children)
    {
        $this->__load();
        return parent::setChildren($children);
    }

    public function addChild(\Application\Model\BusinessUnit $child)
    {
        $this->__load();
        return parent::addChild($child);
    }

    public function getTelephones()
    {
        $this->__load();
        return parent::getTelephones();
    }

    public function setTelephones(\Doctrine\Common\Collections\ArrayCollection $telephones)
    {
        $this->__load();
        return parent::setTelephones($telephones);
    }

    public function addTelephone(\Application\Model\Telephone $telephone)
    {
        $this->__load();
        return parent::addTelephone($telephone);
    }

    public function removeTelephone(\Application\Model\Telephone $telephone)
    {
        $this->__load();
        return parent::removeTelephone($telephone);
    }

    public function addTelephones(\Doctrine\Common\Collections\ArrayCollection $telephones)
    {
        $this->__load();
        return parent::addTelephones($telephones);
    }

    public function removeTelephones(\Doctrine\Common\Collections\ArrayCollection $telephones)
    {
        $this->__load();
        return parent::removeTelephones($telephones);
    }

    public function getUsers()
    {
        $this->__load();
        return parent::getUsers();
    }

    public function setUsers(\Doctrine\Common\Collections\ArrayCollection $users)
    {
        $this->__load();
        return parent::setUsers($users);
    }

    public function addUser(\Application\Model\User $user)
    {
        $this->__load();
        return parent::addUser($user);
    }

    public function equals(\Application\Stdlib\Object $o)
    {
        $this->__load();
        return parent::equals($o);
    }

    public function getAuditableProperties()
    {
        $this->__load();
        return parent::getAuditableProperties();
    }

    public function getClass()
    {
        $this->__load();
        return parent::getClass();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'costCenter', 'description', 'disabledReason', 'divisionName', 'email', 'isDisabled', 'name', 'website', 'creationDate', 'lastUpdateDate', 'organization', 'parentBusinessUnit', 'addresses', 'auditItems', 'children', 'telephones', 'users');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}