<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Model;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Opportunity extends \Application\Model\Opportunity implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getAccount()
    {
        $this->__load();
        return parent::getAccount();
    }

    public function setAccount(\Application\Model\Account $account = NULL)
    {
        $this->__load();
        return parent::setAccount($account);
    }

    public function getActualCloseDate()
    {
        $this->__load();
        return parent::getActualCloseDate();
    }

    public function setActualCloseDate($actualCloseDate = NULL)
    {
        $this->__load();
        return parent::setActualCloseDate($actualCloseDate);
    }

    public function getActualValue()
    {
        $this->__load();
        return parent::getActualValue();
    }

    public function setActualValue($actualValue)
    {
        $this->__load();
        return parent::setActualValue($actualValue);
    }

    public function getBusinessUnit()
    {
        $this->__load();
        return parent::getBusinessUnit();
    }

    public function setBusinessUnit(\Application\Model\BusinessUnit $businessUnit = NULL)
    {
        $this->__load();
        return parent::setBusinessUnit($businessUnit);
    }

    public function getCampaign()
    {
        $this->__load();
        return parent::getCampaign();
    }

    public function setCampaign(\Application\Model\Campaign $campaign = NULL)
    {
        $this->__load();
        return parent::setCampaign($campaign);
    }

    public function getCloseProbability()
    {
        $this->__load();
        return parent::getCloseProbability();
    }

    public function setCloseProbability($closeProbability)
    {
        $this->__load();
        return parent::setCloseProbability($closeProbability);
    }

    public function getConfirmInterest()
    {
        $this->__load();
        return parent::getConfirmInterest();
    }

    public function setConfirmInterest($confirmInterest)
    {
        $this->__load();
        return parent::setConfirmInterest($confirmInterest);
    }

    public function getContact()
    {
        $this->__load();
        return parent::getContact();
    }

    public function setContact(\Application\Model\Contact $contact = NULL)
    {
        $this->__load();
        return parent::setContact($contact);
    }

    public function getCustomerNeed()
    {
        $this->__load();
        return parent::getCustomerNeed();
    }

    public function setCustomerNeed($customerNeed)
    {
        $this->__load();
        return parent::setCustomerNeed($customerNeed);
    }

    public function getCustomerPainPoints()
    {
        $this->__load();
        return parent::getCustomerPainPoints();
    }

    public function setCustomerPainPoints($customerPainPoints)
    {
        $this->__load();
        return parent::setCustomerPainPoints($customerPainPoints);
    }

    public function getDecisionMaker()
    {
        $this->__load();
        return parent::getDecisionMaker();
    }

    public function setDecisionMaker($decisionMaker)
    {
        $this->__load();
        return parent::setDecisionMaker($decisionMaker);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getDevelopProposal()
    {
        $this->__load();
        return parent::getDevelopProposal();
    }

    public function setDevelopProposal($developProposal)
    {
        $this->__load();
        return parent::setDevelopProposal($developProposal);
    }

    public function getEstimatedCloseDate()
    {
        $this->__load();
        return parent::getEstimatedCloseDate();
    }

    public function setEstimatedCloseDate($estimatedCloseDate = NULL)
    {
        $this->__load();
        return parent::setEstimatedCloseDate($estimatedCloseDate);
    }

    public function getEstimatedValue()
    {
        $this->__load();
        return parent::getEstimatedValue();
    }

    public function setEstimatedValue($estimatedValue)
    {
        $this->__load();
        return parent::setEstimatedValue($estimatedValue);
    }

    public function getEvaluateFit()
    {
        $this->__load();
        return parent::getEvaluateFit();
    }

    public function setEvaluateFit($evaluateFit)
    {
        $this->__load();
        return parent::setEvaluateFit($evaluateFit);
    }

    public function getFinalDecisionDate()
    {
        $this->__load();
        return parent::getFinalDecisionDate();
    }

    public function setFinalDecisionDate($finalDecisionDate = NULL)
    {
        $this->__load();
        return parent::setFinalDecisionDate($finalDecisionDate);
    }

    public function getInitialContact()
    {
        $this->__load();
        return parent::getInitialContact();
    }

    public function setInitialContact($initialContact = NULL)
    {
        $this->__load();
        return parent::setInitialContact($initialContact);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getNeed()
    {
        $this->__load();
        return parent::getNeed();
    }

    public function setNeed($need = NULL)
    {
        $this->__load();
        return parent::setNeed($need);
    }

    public function getOpportunityRating()
    {
        $this->__load();
        return parent::getOpportunityRating();
    }

    public function setOpportunityRating($opportunityRating = NULL)
    {
        $this->__load();
        return parent::setOpportunityRating($opportunityRating);
    }

    public function getOriginatingLead()
    {
        $this->__load();
        return parent::getOriginatingLead();
    }

    public function setOriginatingLead(\Application\Model\Lead $lead = NULL)
    {
        $this->__load();
        return parent::setOriginatingLead($lead);
    }

    public function getOwner()
    {
        $this->__load();
        return parent::getOwner();
    }

    public function setOwner(\Application\Model\User $user = NULL)
    {
        $this->__load();
        return parent::setOwner($user);
    }

    public function getPresentProposal()
    {
        $this->__load();
        return parent::getPresentProposal();
    }

    public function setPresentProposal($presentProposal)
    {
        $this->__load();
        return parent::setPresentProposal($presentProposal);
    }

    public function getPriority()
    {
        $this->__load();
        return parent::getPriority();
    }

    public function setPriority($priority = NULL)
    {
        $this->__load();
        return parent::setPriority($priority);
    }

    public function getPurchaseProcess()
    {
        $this->__load();
        return parent::getPurchaseProcess();
    }

    public function setPurchaseProcess($purchaseProcess = NULL)
    {
        $this->__load();
        return parent::setPurchaseProcess($purchaseProcess);
    }

    public function getPurchaseTimeframe()
    {
        $this->__load();
        return parent::getPurchaseTimeframe();
    }

    public function setPurchaseTimeframe($purchaseTimeframe = NULL)
    {
        $this->__load();
        return parent::setPurchaseTimeframe($purchaseTimeframe);
    }

    public function getPursuitDecision()
    {
        $this->__load();
        return parent::getPursuitDecision();
    }

    public function setPursuitDecision($pursuitDecision)
    {
        $this->__load();
        return parent::setPursuitDecision($pursuitDecision);
    }

    public function getQualificationComments()
    {
        $this->__load();
        return parent::getQualificationComments();
    }

    public function setQualificationComments($qualificationComments)
    {
        $this->__load();
        return parent::setQualificationComments($qualificationComments);
    }

    public function getSalesStage()
    {
        $this->__load();
        return parent::getSalesStage();
    }

    public function setSalesStage($salesStage = NULL)
    {
        $this->__load();
        return parent::setSalesStage($salesStage);
    }

    public function getScheduleFollowupProspect()
    {
        $this->__load();
        return parent::getScheduleFollowupProspect();
    }

    public function setScheduleFollowupProspect($scheduleFollowupProspect = NULL)
    {
        $this->__load();
        return parent::setScheduleFollowupProspect($scheduleFollowupProspect);
    }

    public function getScheduleFollowupQualify()
    {
        $this->__load();
        return parent::getScheduleFollowupQualify();
    }

    public function setScheduleFollowupQualify($scheduleFollowupQualify = NULL)
    {
        $this->__load();
        return parent::setScheduleFollowupQualify($scheduleFollowupQualify);
    }

    public function getScheduleProposalMeeting()
    {
        $this->__load();
        return parent::getScheduleProposalMeeting();
    }

    public function setScheduleProposalMeeting($scheduleProposalMeeting = NULL)
    {
        $this->__load();
        return parent::setScheduleProposalMeeting($scheduleProposalMeeting);
    }

    public function getSendThankYou()
    {
        $this->__load();
        return parent::getSendThankYou();
    }

    public function setSendThankYou($sendThankYou)
    {
        $this->__load();
        return parent::setSendThankYou($sendThankYou);
    }

    public function getState()
    {
        $this->__load();
        return parent::getState();
    }

    public function setState($state = NULL)
    {
        $this->__load();
        return parent::setState($state);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setStatus($status = NULL)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getStep()
    {
        $this->__load();
        return parent::getStep();
    }

    public function setStep($step)
    {
        $this->__load();
        return parent::setStep($step);
    }

    public function getTimeline()
    {
        $this->__load();
        return parent::getTimeline();
    }

    public function setTimeline($timeline = NULL)
    {
        $this->__load();
        return parent::setTimeline($timeline);
    }

    public function getCreationDate()
    {
        $this->__load();
        return parent::getCreationDate();
    }

    public function setCreationDate($creationDate)
    {
        $this->__load();
        return parent::setCreationDate($creationDate);
    }

    public function getLastUpdateDate()
    {
        $this->__load();
        return parent::getLastUpdateDate();
    }

    public function setLastUpdateDate($lastUpdateDate)
    {
        $this->__load();
        return parent::setLastUpdateDate($lastUpdateDate);
    }

    public function getOpportunityClose()
    {
        $this->__load();
        return parent::getOpportunityClose();
    }

    public function setOpportunityClose(\Doctrine\Common\Collections\ArrayCollection $opportunityClose)
    {
        $this->__load();
        return parent::setOpportunityClose($opportunityClose);
    }

    public function getAppointments()
    {
        $this->__load();
        return parent::getAppointments();
    }

    public function setAppointments(\Doctrine\Common\Collections\ArrayCollection $appointments)
    {
        $this->__load();
        return parent::setAppointments($appointments);
    }

    public function getAuditItems()
    {
        $this->__load();
        return parent::getAuditItems();
    }

    public function setAuditItems(\Doctrine\Common\Collections\ArrayCollection $auditItems)
    {
        $this->__load();
        return parent::setAuditItems($auditItems);
    }

    public function addAuditItem(\Application\Model\Audit $auditItem)
    {
        $this->__load();
        return parent::addAuditItem($auditItem);
    }

    public function removeAuditItem(\Application\Model\Audit $auditItem)
    {
        $this->__load();
        return parent::removeAuditItem($auditItem);
    }

    public function getInteractions()
    {
        $this->__load();
        return parent::getInteractions();
    }

    public function setInteractions(\Doctrine\Common\Collections\ArrayCollection $interactions)
    {
        $this->__load();
        return parent::setInteractions($interactions);
    }

    public function getNotes()
    {
        $this->__load();
        return parent::getNotes();
    }

    public function setNotes(\Doctrine\Common\Collections\ArrayCollection $notes)
    {
        $this->__load();
        return parent::setNotes($notes);
    }

    public function getTasks()
    {
        $this->__load();
        return parent::getTasks();
    }

    public function setTasks(\Doctrine\Common\Collections\ArrayCollection $tasks)
    {
        $this->__load();
        return parent::setTasks($tasks);
    }

    public function addOpportunityClose(\Application\Model\OpportunityClose $opportunityClose)
    {
        $this->__load();
        return parent::addOpportunityClose($opportunityClose);
    }

    public function addAppointment(\Application\Model\AbstractAppointment $appointment)
    {
        $this->__load();
        return parent::addAppointment($appointment);
    }

    public function addInteraction(\Application\Model\AbstractInteraction $interaction)
    {
        $this->__load();
        return parent::addInteraction($interaction);
    }

    public function addNote(\Application\Model\AbstractNote $note)
    {
        $this->__load();
        return parent::addNote($note);
    }

    public function addTask(\Application\Model\AbstractTask $task)
    {
        $this->__load();
        return parent::addTask($task);
    }

    public function compareTo(\Application\Stdlib\Object $value = NULL)
    {
        $this->__load();
        return parent::compareTo($value);
    }

    public function equals(\Application\Stdlib\Object $o)
    {
        $this->__load();
        return parent::equals($o);
    }

    public function getAuditableProperties()
    {
        $this->__load();
        return parent::getAuditableProperties();
    }

    public function getClass()
    {
        $this->__load();
        return parent::getClass();
    }

    public function getDisplayName($includeLink = false)
    {
        $this->__load();
        return parent::getDisplayName($includeLink);
    }

    public function getFormattedActualCloseDate($format = NULL)
    {
        $this->__load();
        return parent::getFormattedActualCloseDate($format);
    }

    public function getFormattedEstimatedCloseDate($format = NULL)
    {
        $this->__load();
        return parent::getFormattedEstimatedCloseDate($format);
    }

    public function getFormattedFinalDecisionDate($format = NULL)
    {
        $this->__load();
        return parent::getFormattedFinalDecisionDate($format);
    }

    public function getFormattedScheduleFollowupProspect($format = NULL)
    {
        $this->__load();
        return parent::getFormattedScheduleFollowupProspect($format);
    }

    public function getFormattedScheduleFollowupQualify($format = NULL)
    {
        $this->__load();
        return parent::getFormattedScheduleFollowupQualify($format);
    }

    public function getFormattedScheduleProposalMeeting($format = NULL)
    {
        $this->__load();
        return parent::getFormattedScheduleProposalMeeting($format);
    }

    public function getOpenActivities()
    {
        $this->__load();
        return parent::getOpenActivities();
    }

    public function getClosedActivities()
    {
        $this->__load();
        return parent::getClosedActivities();
    }

    public function getPotentialCustomer()
    {
        $this->__load();
        return parent::getPotentialCustomer();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'actualCloseDate', 'actualValue', 'closeProbability', 'confirmInterest', 'customerNeed', 'customerPainPoints', 'decisionMaker', 'description', 'developProposal', 'estimatedCloseDate', 'estimatedValue', 'evaluateFit', 'finalDecisionDate', 'initialContact', 'name', 'need', 'opportunityRating', 'presentProposal', 'priority', 'purchaseProcess', 'purchaseTimeframe', 'pursuitDecision', 'qualificationComments', 'salesStage', 'scheduleFollowupProspect', 'scheduleFollowupQualify', 'scheduleProposalMeeting', 'sendThankYou', 'state', 'status', 'step', 'timeline', 'creationDate', 'lastUpdateDate', 'account', 'businessUnit', 'campaign', 'contact', 'originatingLead', 'owner', 'appointments', 'auditItems', 'interactions', 'notes', 'tasks', 'opportunityClose');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}