<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Model;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Organization extends \Application\Model\Organization implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getDateFormat()
    {
        $this->__load();
        return parent::getDateFormat();
    }

    public function setDateFormat($dateFormat)
    {
        $this->__load();
        return parent::setDateFormat($dateFormat);
    }

    public function getDisabledReason()
    {
        $this->__load();
        return parent::getDisabledReason();
    }

    public function setDisabledReason($disabledReason)
    {
        $this->__load();
        return parent::setDisabledReason($disabledReason);
    }

    public function getIsDisabled()
    {
        $this->__load();
        return parent::getIsDisabled();
    }

    public function setIsDisabled($isDisabled)
    {
        $this->__load();
        return parent::setIsDisabled($isDisabled);
    }

    public function getLocale()
    {
        $this->__load();
        return parent::getLocale();
    }

    public function setLocale($locale)
    {
        $this->__load();
        return parent::setLocale($locale);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getCreationDate()
    {
        $this->__load();
        return parent::getCreationDate();
    }

    public function setCreationDate($creationDate)
    {
        $this->__load();
        return parent::setCreationDate($creationDate);
    }

    public function getLastUpdateDate()
    {
        $this->__load();
        return parent::getLastUpdateDate();
    }

    public function setLastUpdateDate($lastUpdateDate)
    {
        $this->__load();
        return parent::setLastUpdateDate($lastUpdateDate);
    }

    public function getBusinessUnits()
    {
        $this->__load();
        return parent::getBusinessUnits();
    }

    public function setBusinessUnits(\Doctrine\Common\Collections\ArrayCollection $businessUnits)
    {
        $this->__load();
        return parent::setBusinessUnits($businessUnits);
    }

    public function addBusinessUnit(\Application\Model\BusinessUnit $businessUnit)
    {
        $this->__load();
        return parent::addBusinessUnit($businessUnit);
    }

    public function removeBusinessUnit(\Application\Model\BusinessUnit $businessUnit)
    {
        $this->__load();
        return parent::removeBusinessUnit($businessUnit);
    }

    public function equals(\Application\Stdlib\Object $o)
    {
        $this->__load();
        return parent::equals($o);
    }

    public function getClass()
    {
        $this->__load();
        return parent::getClass();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'dateFormat', 'disabledReason', 'isDisabled', 'locale', 'name', 'creationDate', 'lastUpdateDate', 'businessUnits');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}