<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Model;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CampaignActivity extends \Application\Model\CampaignActivity implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getChannelType()
    {
        $this->__load();
        return parent::getChannelType();
    }

    public function setChannelType($channelType = NULL)
    {
        $this->__load();
        return parent::setChannelType($channelType);
    }

    public function getDiscriminator()
    {
        $this->__load();
        return parent::getDiscriminator();
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setStatus($status = NULL)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function setType($type = NULL)
    {
        $this->__load();
        return parent::setType($type);
    }

    public function getAnnotations()
    {
        $this->__load();
        return parent::getAnnotations();
    }

    public function setAnnotations(\Doctrine\Common\Collections\ArrayCollection $annotations)
    {
        $this->__load();
        return parent::setAnnotations($annotations);
    }

    public function addAnnotation(\Application\Model\AbstractNote $annotation)
    {
        $this->__load();
        return parent::addAnnotation($annotation);
    }

    public function removeAnnotation(\Application\Model\AbstractNote $annotation)
    {
        $this->__load();
        return parent::removeAnnotation($annotation);
    }

    public function getAppointments()
    {
        $this->__load();
        return parent::getAppointments();
    }

    public function setAppointments(\Doctrine\Common\Collections\ArrayCollection $appointments)
    {
        $this->__load();
        return parent::setAppointments($appointments);
    }

    public function addAppointment(\Application\Model\AbstractAppointment $appointment)
    {
        $this->__load();
        return parent::addAppointment($appointment);
    }

    public function removeAppointment(\Application\Model\AbstractAppointment $appointment)
    {
        $this->__load();
        return parent::removeAppointment($appointment);
    }

    public function getBulkOperations()
    {
        $this->__load();
        return parent::getBulkOperations();
    }

    public function setBulkOperations(\Doctrine\Common\Collections\ArrayCollection $bulkOperations)
    {
        $this->__load();
        return parent::setBulkOperations($bulkOperations);
    }

    public function addBulkOperation(\Application\Model\BulkOperation $bulkOperation)
    {
        $this->__load();
        return parent::addBulkOperation($bulkOperation);
    }

    public function removeBulkOperation(\Application\Model\BulkOperation $bulkOperation)
    {
        $this->__load();
        return parent::removeBulkOperation($bulkOperation);
    }

    public function getInteractions()
    {
        $this->__load();
        return parent::getInteractions();
    }

    public function setInteractions(\Doctrine\Common\Collections\ArrayCollection $interactions)
    {
        $this->__load();
        return parent::setInteractions($interactions);
    }

    public function addInteraction(\Application\Model\AbstractInteraction $interaction)
    {
        $this->__load();
        return parent::addInteraction($interaction);
    }

    public function removeInteraction(\Application\Model\AbstractInteraction $interaction)
    {
        $this->__load();
        return parent::removeInteraction($interaction);
    }

    public function getTasks()
    {
        $this->__load();
        return parent::getTasks();
    }

    public function setTasks(\Doctrine\Common\Collections\ArrayCollection $tasks)
    {
        $this->__load();
        return parent::setTasks($tasks);
    }

    public function addTask(\Application\Model\AbstractTask $task)
    {
        $this->__load();
        return parent::addTask($task);
    }

    public function removeTask(\Application\Model\AbstractTask $task)
    {
        $this->__load();
        return parent::removeTask($task);
    }

    public function getLists()
    {
        $this->__load();
        return parent::getLists();
    }

    public function getListsAsArray()
    {
        $this->__load();
        return parent::getListsAsArray();
    }

    public function setLists(\Doctrine\Common\Collections\ArrayCollection $lists)
    {
        $this->__load();
        return parent::setLists($lists);
    }

    public function addList(\Application\Model\MarketingList $list)
    {
        $this->__load();
        return parent::addList($list);
    }

    public function removeList(\Application\Model\MarketingList $list)
    {
        $this->__load();
        return parent::removeList($list);
    }

    public function getSalesLiterature()
    {
        $this->__load();
        return parent::getSalesLiterature();
    }

    public function setSalesLiterature(\Doctrine\Common\Collections\ArrayCollection $salesLiterature)
    {
        $this->__load();
        return parent::setSalesLiterature($salesLiterature);
    }

    public function addSalesLiterature(\Application\Model\SalesLiterature $salesLiterature)
    {
        $this->__load();
        return parent::addSalesLiterature($salesLiterature);
    }

    public function removeSalesLiterature(\Application\Model\SalesLiterature $salesLiterature)
    {
        $this->__load();
        return parent::removeSalesLiterature($salesLiterature);
    }

    public function getClosedActivities()
    {
        $this->__load();
        return parent::getClosedActivities();
    }

    public function getDisplayName($includeLink = false)
    {
        $this->__load();
        return parent::getDisplayName($includeLink);
    }

    public function getOpenActivities()
    {
        $this->__load();
        return parent::getOpenActivities();
    }

    public function removeMatchedCandidates(array $candidates)
    {
        $this->__load();
        return parent::removeMatchedCandidates($candidates);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getActualStart()
    {
        $this->__load();
        return parent::getActualStart();
    }

    public function setActualStart($actualStart = NULL, $bypassFilter = false)
    {
        $this->__load();
        return parent::setActualStart($actualStart, $bypassFilter);
    }

    public function getActualEnd()
    {
        $this->__load();
        return parent::getActualEnd();
    }

    public function setActualEnd($actualEnd = NULL, $bypassFilter = false)
    {
        $this->__load();
        return parent::setActualEnd($actualEnd, $bypassFilter);
    }

    public function equals(\Application\Stdlib\Object $o)
    {
        $this->__load();
        return parent::equals($o);
    }

    public function getFormattedActualEnd($format = NULL)
    {
        $this->__load();
        return parent::getFormattedActualEnd($format);
    }

    public function getFormattedActualStart($format = NULL)
    {
        $this->__load();
        return parent::getFormattedActualStart($format);
    }

    public function getScheduledStart()
    {
        $this->__load();
        return parent::getScheduledStart();
    }

    public function setScheduledStart($scheduledStart)
    {
        $this->__load();
        return parent::setScheduledStart($scheduledStart);
    }

    public function getScheduledEnd()
    {
        $this->__load();
        return parent::getScheduledEnd();
    }

    public function setScheduledEnd($scheduledEnd)
    {
        $this->__load();
        return parent::setScheduledEnd($scheduledEnd);
    }

    public function getFormattedScheduledEnd($format = NULL)
    {
        $this->__load();
        return parent::getFormattedScheduledEnd($format);
    }

    public function getFormattedScheduledStart($format = NULL)
    {
        $this->__load();
        return parent::getFormattedScheduledStart($format);
    }

    public function getPriority()
    {
        $this->__load();
        return parent::getPriority();
    }

    public function setPriority($priority = NULL)
    {
        $this->__load();
        return parent::setPriority($priority);
    }

    public function getState()
    {
        $this->__load();
        return parent::getState();
    }

    public function setState($state = NULL)
    {
        $this->__load();
        return parent::setState($state);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setDiscriminator($discriminator)
    {
        $this->__load();
        return parent::setDiscriminator($discriminator);
    }

    public function getAccount()
    {
        $this->__load();
        return parent::getAccount();
    }

    public function setAccount(\Application\Model\Account $account = NULL)
    {
        $this->__load();
        return parent::setAccount($account);
    }

    public function getBusinessUnit()
    {
        $this->__load();
        return parent::getBusinessUnit();
    }

    public function setBusinessUnit(\Application\Model\BusinessUnit $businessUnit = NULL)
    {
        $this->__load();
        return parent::setBusinessUnit($businessUnit);
    }

    public function getCampaign()
    {
        $this->__load();
        return parent::getCampaign();
    }

    public function setCampaign(\Application\Model\Campaign $campaign = NULL)
    {
        $this->__load();
        return parent::setCampaign($campaign);
    }

    public function getCampaignActivity()
    {
        $this->__load();
        return parent::getCampaignActivity();
    }

    public function setCampaignActivity(\Application\Model\CampaignActivity $campaignActivity = NULL)
    {
        $this->__load();
        return parent::setCampaignActivity($campaignActivity);
    }

    public function getContact()
    {
        $this->__load();
        return parent::getContact();
    }

    public function setContact(\Application\Model\Contact $contact = NULL)
    {
        $this->__load();
        return parent::setContact($contact);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getLead()
    {
        $this->__load();
        return parent::getLead();
    }

    public function setLead(\Application\Model\Lead $lead = NULL)
    {
        $this->__load();
        return parent::setLead($lead);
    }

    public function getLongNotes()
    {
        $this->__load();
        return parent::getLongNotes();
    }

    public function setLongNotes($longNotes)
    {
        $this->__load();
        return parent::setLongNotes($longNotes);
    }

    public function getNotes()
    {
        $this->__load();
        return parent::getNotes();
    }

    public function setNotes($notes)
    {
        $this->__load();
        return parent::setNotes($notes);
    }

    public function getOpportunity()
    {
        $this->__load();
        return parent::getOpportunity();
    }

    public function setOpportunity(\Application\Model\Opportunity $opportunity = NULL)
    {
        $this->__load();
        return parent::setOpportunity($opportunity);
    }

    public function getOwner()
    {
        $this->__load();
        return parent::getOwner();
    }

    public function setOwner(\Application\Model\User $user = NULL)
    {
        $this->__load();
        return parent::setOwner($user);
    }

    public function getSubject()
    {
        $this->__load();
        return parent::getSubject();
    }

    public function setSubject($subject)
    {
        $this->__load();
        return parent::setSubject($subject);
    }

    public function getCreationDate()
    {
        $this->__load();
        return parent::getCreationDate();
    }

    public function setCreationDate($creationDate)
    {
        $this->__load();
        return parent::setCreationDate($creationDate);
    }

    public function getLastUpdateDate()
    {
        $this->__load();
        return parent::getLastUpdateDate();
    }

    public function setLastUpdateDate($lastUpdateDate)
    {
        $this->__load();
        return parent::setLastUpdateDate($lastUpdateDate);
    }

    public function getAuditItems()
    {
        $this->__load();
        return parent::getAuditItems();
    }

    public function setAuditItems(\Doctrine\Common\Collections\ArrayCollection $auditItems)
    {
        $this->__load();
        return parent::setAuditItems($auditItems);
    }

    public function addAuditItem(\Application\Model\Audit $auditItem)
    {
        $this->__load();
        return parent::addAuditItem($auditItem);
    }

    public function removeAuditItem(\Application\Model\Audit $auditItem)
    {
        $this->__load();
        return parent::removeAuditItem($auditItem);
    }

    public function getAuditableProperties()
    {
        $this->__load();
        return parent::getAuditableProperties();
    }

    public function getClass()
    {
        $this->__load();
        return parent::getClass();
    }

    public function getDescriptionLink($id = NULL, $route = NULL)
    {
        $this->__load();
        return parent::getDescriptionLink($id, $route);
    }

    public function getDiscriminatorTitle()
    {
        $this->__load();
        return parent::getDiscriminatorTitle();
    }

    public function getListTitle()
    {
        $this->__load();
        return parent::getListTitle();
    }

    public function getRegardingObject()
    {
        $this->__load();
        return parent::getRegardingObject();
    }

    public function getRegardingObjectName($includeLink = false)
    {
        $this->__load();
        return parent::getRegardingObjectName($includeLink);
    }

    public function getTopic()
    {
        $this->__load();
        return parent::getTopic();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'description', 'longNotes', 'notes', 'subject', 'creationDate', 'lastUpdateDate', 'account', 'businessUnit', 'campaign', 'campaignActivity', 'contact', 'lead', 'opportunity', 'owner', 'auditItems', 'priority', 'state', 'status', 'scheduledStart', 'scheduledEnd', 'actualStart', 'actualEnd', 'channelType', 'type', 'annotations', 'appointments', 'bulkOperations', 'interactions', 'tasks', 'lists', 'salesLiterature');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}