<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Model;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Lead extends \Application\Model\Lead implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getAccount()
    {
        $this->__load();
        return parent::getAccount();
    }

    public function setAccount(\Application\Model\Account $account = NULL)
    {
        $this->__load();
        return parent::setAccount($account);
    }

    public function getBusinessUnit()
    {
        $this->__load();
        return parent::getBusinessUnit();
    }

    public function setBusinessUnit(\Application\Model\BusinessUnit $businessUnit = NULL)
    {
        $this->__load();
        return parent::setBusinessUnit($businessUnit);
    }

    public function getCampaign()
    {
        $this->__load();
        return parent::getCampaign();
    }

    public function setCampaign(\Application\Model\Campaign $campaign = NULL)
    {
        $this->__load();
        return parent::setCampaign($campaign);
    }

    public function getCompanyName()
    {
        $this->__load();
        return parent::getCompanyName();
    }

    public function setCompanyName($companyName)
    {
        $this->__load();
        return parent::setCompanyName($companyName);
    }

    public function getConfirmInterest()
    {
        $this->__load();
        return parent::getConfirmInterest();
    }

    public function setConfirmInterest($confirmInterest)
    {
        $this->__load();
        return parent::setConfirmInterest($confirmInterest);
    }

    public function getContact()
    {
        $this->__load();
        return parent::getContact();
    }

    public function setContact(\Application\Model\Contact $contact = NULL)
    {
        $this->__load();
        return parent::setContact($contact);
    }

    public function getDecisionMaker()
    {
        $this->__load();
        return parent::getDecisionMaker();
    }

    public function setDecisionMaker($decisionMaker)
    {
        $this->__load();
        return parent::setDecisionMaker($decisionMaker);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getDoNotEmail()
    {
        $this->__load();
        return parent::getDoNotEmail();
    }

    public function setDoNotEmail($doNotEmail)
    {
        $this->__load();
        return parent::setDoNotEmail($doNotEmail);
    }

    public function getDoNotMail()
    {
        $this->__load();
        return parent::getDoNotMail();
    }

    public function setDoNotMail($doNotMail)
    {
        $this->__load();
        return parent::setDoNotMail($doNotMail);
    }

    public function getDoNotPhone()
    {
        $this->__load();
        return parent::getDoNotPhone();
    }

    public function setDoNotPhone($doNotPhone)
    {
        $this->__load();
        return parent::setDoNotPhone($doNotPhone);
    }

    public function getEmail1()
    {
        $this->__load();
        return parent::getEmail1();
    }

    public function setEmail1($email1)
    {
        $this->__load();
        return parent::setEmail1($email1);
    }

    public function getEmail2()
    {
        $this->__load();
        return parent::getEmail2();
    }

    public function setEmail2($email2)
    {
        $this->__load();
        return parent::setEmail2($email2);
    }

    public function getEstimatedCloseDate()
    {
        $this->__load();
        return parent::getEstimatedCloseDate();
    }

    public function setEstimatedCloseDate($estimatedCloseDate = NULL)
    {
        $this->__load();
        return parent::setEstimatedCloseDate($estimatedCloseDate);
    }

    public function getEstimatedValue()
    {
        $this->__load();
        return parent::getEstimatedValue();
    }

    public function setEstimatedValue($estimatedValue)
    {
        $this->__load();
        return parent::setEstimatedValue($estimatedValue);
    }

    public function getEvaluateFit()
    {
        $this->__load();
        return parent::getEvaluateFit();
    }

    public function setEvaluateFit($evaluateFit)
    {
        $this->__load();
        return parent::setEvaluateFit($evaluateFit);
    }

    public function getFirstName()
    {
        $this->__load();
        return parent::getFirstName();
    }

    public function setFirstName($firstName)
    {
        $this->__load();
        return parent::setFirstName($firstName);
    }

    public function getFullName()
    {
        $this->__load();
        return parent::getFullName();
    }

    public function setFullName($fullName)
    {
        $this->__load();
        return parent::setFullName($fullName);
    }

    public function getInitialContact()
    {
        $this->__load();
        return parent::getInitialContact();
    }

    public function setInitialContact($initialContact = NULL)
    {
        $this->__load();
        return parent::setInitialContact($initialContact);
    }

    public function getJobTitle()
    {
        $this->__load();
        return parent::getJobTitle();
    }

    public function setJobTitle($jobTitle)
    {
        $this->__load();
        return parent::setJobTitle($jobTitle);
    }

    public function getLastName()
    {
        $this->__load();
        return parent::getLastName();
    }

    public function setLastName($lastName)
    {
        $this->__load();
        return parent::setLastName($lastName);
    }

    public function getLeadQuality()
    {
        $this->__load();
        return parent::getLeadQuality();
    }

    public function setLeadQuality($leadQuality = NULL)
    {
        $this->__load();
        return parent::setLeadQuality($leadQuality);
    }

    public function getLeadSource()
    {
        $this->__load();
        return parent::getLeadSource();
    }

    public function setLeadSource($leadSource)
    {
        $this->__load();
        return parent::setLeadSource($leadSource);
    }

    public function getMiddleName()
    {
        $this->__load();
        return parent::getMiddleName();
    }

    public function setMiddleName($middleName)
    {
        $this->__load();
        return parent::setMiddleName($middleName);
    }

    public function getNeed()
    {
        $this->__load();
        return parent::getNeed();
    }

    public function setNeed($need = NULL)
    {
        $this->__load();
        return parent::setNeed($need);
    }

    public function getOpportunity()
    {
        $this->__load();
        return parent::getOpportunity();
    }

    public function setOpportunity(\Application\Model\Opportunity $opportunity = NULL)
    {
        $this->__load();
        return parent::setOpportunity($opportunity);
    }

    public function getOwner()
    {
        $this->__load();
        return parent::getOwner();
    }

    public function setOwner(\Application\Model\User $user = NULL)
    {
        $this->__load();
        return parent::setOwner($user);
    }

    public function getPrefix()
    {
        $this->__load();
        return parent::getPrefix();
    }

    public function setPrefix($prefix)
    {
        $this->__load();
        return parent::setPrefix($prefix);
    }

    public function getPriority()
    {
        $this->__load();
        return parent::getPriority();
    }

    public function setPriority($priority = NULL)
    {
        $this->__load();
        return parent::setPriority($priority);
    }

    public function getPurchaseProcess()
    {
        $this->__load();
        return parent::getPurchaseProcess();
    }

    public function setPurchaseProcess($purchaseProcess = NULL)
    {
        $this->__load();
        return parent::setPurchaseProcess($purchaseProcess);
    }

    public function getPurchaseTimeframe()
    {
        $this->__load();
        return parent::getPurchaseTimeframe();
    }

    public function setPurchaseTimeframe($purchaseTimeframe = NULL)
    {
        $this->__load();
        return parent::setPurchaseTimeframe($purchaseTimeframe);
    }

    public function getQualificationComments()
    {
        $this->__load();
        return parent::getQualificationComments();
    }

    public function setQualificationComments($qualificationComments)
    {
        $this->__load();
        return parent::setQualificationComments($qualificationComments);
    }

    public function getRevenue()
    {
        $this->__load();
        return parent::getRevenue();
    }

    public function setRevenue($revenue)
    {
        $this->__load();
        return parent::setRevenue($revenue);
    }

    public function getSalesStage()
    {
        $this->__load();
        return parent::getSalesStage();
    }

    public function setSalesStage($salesStage = NULL)
    {
        $this->__load();
        return parent::setSalesStage($salesStage);
    }

    public function getSalesStageCode()
    {
        $this->__load();
        return parent::getSalesStageCode();
    }

    public function setSalesStageCode($salesStageCode)
    {
        $this->__load();
        return parent::setSalesStageCode($salesStageCode);
    }

    public function getSalutation()
    {
        $this->__load();
        return parent::getSalutation();
    }

    public function setSalutation($salutation = NULL)
    {
        $this->__load();
        return parent::setSalutation($salutation);
    }

    public function getScheduleFollowupProspect()
    {
        $this->__load();
        return parent::getScheduleFollowupProspect();
    }

    public function setScheduleFollowupProspect($scheduleFollowupProspect = NULL)
    {
        $this->__load();
        return parent::setScheduleFollowupProspect($scheduleFollowupProspect);
    }

    public function getScheduleFollowupQualify()
    {
        $this->__load();
        return parent::getScheduleFollowupQualify();
    }

    public function setScheduleFollowupQualify($scheduleFollowupQualify = NULL)
    {
        $this->__load();
        return parent::setScheduleFollowupQualify($scheduleFollowupQualify);
    }

    public function getState()
    {
        $this->__load();
        return parent::getState();
    }

    public function setState($state = NULL)
    {
        $this->__load();
        return parent::setState($state);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setStatus($status = NULL)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getSuffix()
    {
        $this->__load();
        return parent::getSuffix();
    }

    public function setSuffix($suffix)
    {
        $this->__load();
        return parent::setSuffix($suffix);
    }

    public function getWebsite()
    {
        $this->__load();
        return parent::getWebsite();
    }

    public function setWebsite($website)
    {
        $this->__load();
        return parent::setWebsite($website);
    }

    public function getCreationDate()
    {
        $this->__load();
        return parent::getCreationDate();
    }

    public function setCreationDate($creationDate)
    {
        $this->__load();
        return parent::setCreationDate($creationDate);
    }

    public function getLastUpdateDate()
    {
        $this->__load();
        return parent::getLastUpdateDate();
    }

    public function setLastUpdateDate($lastUpdateDate)
    {
        $this->__load();
        return parent::setLastUpdateDate($lastUpdateDate);
    }

    public function getAddresses()
    {
        $this->__load();
        return parent::getAddresses();
    }

    public function setAddresses(\Doctrine\Common\Collections\ArrayCollection $addresses)
    {
        $this->__load();
        return parent::setAddresses($addresses);
    }

    public function addAddresses(\Doctrine\Common\Collections\ArrayCollection $addresses)
    {
        $this->__load();
        return parent::addAddresses($addresses);
    }

    public function removeAddresses(\Doctrine\Common\Collections\ArrayCollection $addresses)
    {
        $this->__load();
        return parent::removeAddresses($addresses);
    }

    public function addAddress(\Application\Model\Address $address)
    {
        $this->__load();
        return parent::addAddress($address);
    }

    public function removeAddress(\Application\Model\Address $address)
    {
        $this->__load();
        return parent::removeAddress($address);
    }

    public function getAppointments()
    {
        $this->__load();
        return parent::getAppointments();
    }

    public function setAppointments(\Doctrine\Common\Collections\ArrayCollection $appointments)
    {
        $this->__load();
        return parent::setAppointments($appointments);
    }

    public function addAppointment(\Application\Model\AbstractAppointment $appointment)
    {
        $this->__load();
        return parent::addAppointment($appointment);
    }

    public function getAuditItems()
    {
        $this->__load();
        return parent::getAuditItems();
    }

    public function setAuditItems(\Doctrine\Common\Collections\ArrayCollection $auditItems)
    {
        $this->__load();
        return parent::setAuditItems($auditItems);
    }

    public function addAuditItem(\Application\Model\Audit $auditItem)
    {
        $this->__load();
        return parent::addAuditItem($auditItem);
    }

    public function removeAuditItem(\Application\Model\Audit $auditItem)
    {
        $this->__load();
        return parent::removeAuditItem($auditItem);
    }

    public function getInteractions()
    {
        $this->__load();
        return parent::getInteractions();
    }

    public function setInteractions(\Doctrine\Common\Collections\ArrayCollection $interactions)
    {
        $this->__load();
        return parent::setInteractions($interactions);
    }

    public function addInteraction(\Application\Model\AbstractInteraction $interaction)
    {
        $this->__load();
        return parent::addInteraction($interaction);
    }

    public function getLists()
    {
        $this->__load();
        return parent::getLists();
    }

    public function setLists(\Doctrine\Common\Collections\ArrayCollection $lists)
    {
        $this->__load();
        return parent::setLists($lists);
    }

    public function addList(\Application\Model\MarketingList $list)
    {
        $this->__load();
        return parent::addList($list);
    }

    public function removeList(\Application\Model\MarketingList $list)
    {
        $this->__load();
        return parent::removeList($list);
    }

    public function getNotes()
    {
        $this->__load();
        return parent::getNotes();
    }

    public function setNotes(\Doctrine\Common\Collections\ArrayCollection $notes)
    {
        $this->__load();
        return parent::setNotes($notes);
    }

    public function addNote(\Application\Model\AbstractNote $note)
    {
        $this->__load();
        return parent::addNote($note);
    }

    public function getOpportunities()
    {
        $this->__load();
        return parent::getOpportunities();
    }

    public function setOpportunities(\Doctrine\Common\Collections\ArrayCollection $opportunities)
    {
        $this->__load();
        return parent::setOpportunities($opportunities);
    }

    public function addOpportunity(\Application\Model\Opportunity $opportunity)
    {
        $this->__load();
        return parent::addOpportunity($opportunity);
    }

    public function getTasks()
    {
        $this->__load();
        return parent::getTasks();
    }

    public function setTasks(\Doctrine\Common\Collections\ArrayCollection $tasks)
    {
        $this->__load();
        return parent::setTasks($tasks);
    }

    public function addTask(\Application\Model\AbstractTask $task)
    {
        $this->__load();
        return parent::addTask($task);
    }

    public function getTelephones()
    {
        $this->__load();
        return parent::getTelephones();
    }

    public function setTelephones(\Doctrine\Common\Collections\ArrayCollection $telephones)
    {
        $this->__load();
        return parent::setTelephones($telephones);
    }

    public function addTelephones(\Doctrine\Common\Collections\ArrayCollection $telephones)
    {
        $this->__load();
        return parent::addTelephones($telephones);
    }

    public function removeTelephones(\Doctrine\Common\Collections\ArrayCollection $telephones)
    {
        $this->__load();
        return parent::removeTelephones($telephones);
    }

    public function addTelephone(\Application\Model\Telephone $telephone)
    {
        $this->__load();
        return parent::addTelephone($telephone);
    }

    public function removeTelephone(\Application\Model\Telephone $telephone)
    {
        $this->__load();
        return parent::removeTelephone($telephone);
    }

    public function computeFullName()
    {
        $this->__load();
        return parent::computeFullName();
    }

    public function equals(\Application\Stdlib\Object $o)
    {
        $this->__load();
        return parent::equals($o);
    }

    public function getAuditableProperties()
    {
        $this->__load();
        return parent::getAuditableProperties();
    }

    public function getClass()
    {
        $this->__load();
        return parent::getClass();
    }

    public function getClosedActivities()
    {
        $this->__load();
        return parent::getClosedActivities();
    }

    public function getDisplayName($includeLink = false)
    {
        $this->__load();
        return parent::getDisplayName($includeLink);
    }

    public function getEmailLink()
    {
        $this->__load();
        return parent::getEmailLink();
    }

    public function getOpenActivities()
    {
        $this->__load();
        return parent::getOpenActivities();
    }

    public function getPrimaryAddress()
    {
        $this->__load();
        return parent::getPrimaryAddress();
    }

    public function getPrimaryTelephone()
    {
        $this->__load();
        return parent::getPrimaryTelephone();
    }

    public function getSmtpEmailAddress()
    {
        $this->__load();
        return parent::getSmtpEmailAddress();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'companyName', 'confirmInterest', 'decisionMaker', 'description', 'doNotEmail', 'doNotMail', 'doNotPhone', 'email1', 'email2', 'estimatedCloseDate', 'estimatedValue', 'evaluateFit', 'firstName', 'fullName', 'initialContact', 'jobTitle', 'lastName', 'leadQuality', 'leadSource', 'middleName', 'need', 'prefix', 'priority', 'purchaseProcess', 'purchaseTimeframe', 'qualificationComments', 'revenue', 'salesStage', 'salesStageCode', 'salutation', 'scheduleFollowupProspect', 'scheduleFollowupQualify', 'state', 'status', 'suffix', 'website', 'creationDate', 'lastUpdateDate', 'account', 'businessUnit', 'campaign', 'contact', 'opportunity', 'owner', 'addresses', 'appointments', 'auditItems', 'interactions', 'notes', 'opportunities', 'tasks', 'telephones', 'lists');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}