<?php

/**
 * Casales Library
 * PHP version 5.4
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * KAATERSKIL MANAGEMENT, LLC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category Casales
 * @package Application
 * @copyright Copyright (c) 2009-2013 Kaaterskil Management, LLC
 * @version SVN $Id: closedIndex.phtml 13 2013-08-05 22:53:55Z  $
 */
use Application\Model\Account;
use Application\Model\Opportunity;

/* @var $obj Opportunity */
/* @var $account Account */

// Set page title
$this->headTitle()->append($this->pageTitle);
$this->headTitle()->append('Casales');
?>
<div class="grid_12">
	<div class="entity-type">Opportunity</div>
	<h1 class="page-title">
		<?php echo $this->pageTitle; ?>
	</h1>
	<div class="table-container">
		<table>
			<thead class="fixed-thead">
				<tr>
					<th width="70"></th>
					<th width="300">Description</th>
					<th width="210">Potential Customer</th>
					<th width="140">Status</th>
					<th width="100">Actual Revenue</th>
					<th width="118">Actual Close Date</th>
				</tr>
			</thead>
			<tbody class="scrollable-tbody">
				<?php if(count($this->recordSet)) : ?>
				<?php foreach ($this->recordSet as $obj) : ?>
				<tr>
					<td width="70"><a href="<?php echo $this->url('opportunity', array('action' => 'edit', 'id' => $obj->getId())); ?>">Edit</a>
						<a href="<?php echo $this->url('opportunity', array('action' => 'delete', 'id' => $obj->getId())); ?>">Delete</a>
					</td>
					<td width="300"><?php echo $obj->getDescription(); ?></td>
					<td width="210"><?php echo $obj->getPotentialCustomer(); ?></td>
					<td width="140"><?php echo $obj->getStatus(); ?></td>
					<td width="100"><?php echo $obj->getActualValue(); ?></td>
					<td width="102"><?php echo $obj->getFormattedActualCloseDate('m/d/Y'); ?></td>
				</tr>
				<?php endforeach; ?>
				<?php else : ?>
				<tr>
					<td colspan="6" class="no-records">No records found.</td>
				</tr>
				<?php endif; ?>
			</tbody>
		</table>
	</div>
</div>
<div class="clearfix"></div>
<div class="grid_12">
	<div class="bottom-status-bar"><?php echo $this->statusMessage; ?></div>
</div>
