<?php

/**
 * Casales Library
 * PHP version 5.4
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * KAATERSKIL MANAGEMENT, LLC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category Casales
 * @package Application
 * @copyright Copyright (c) 2009-2013 Kaaterskil Management, LLC
 * @version SVN $Id: loseOpportunity.phtml 13 2013-08-05 22:53:55Z  $
 */
use Application\Form\LoseOpportunityForm;
use Zend\Form\View\Helper\FormRow;

/* @var $lof LoseOpportunityForm */

$lof = $this->loseOpportunityForm;
$lof->setAttributes( array(
	'action' => $this->url( 'opportunity', array(
		'action' => 'loseOpportunity',
		'id' => $this->id,
	) ),
	'method' => 'post',
	'name' => 'lose_opportunity'
) );
?>
<div class="lose-opportunity-dialog">
	<h2 class="dialog-title">Close Opportunity</h2>
	<div class="">Provide the following information about why the opportunity is being closed.</div>
	<div class="">
		<?php echo $this->form()->openTag($lof); ?>
		<?php echo $this->formRow($lof->get(LoseOpportunityForm::STATUS)); ?>
		<?php echo $this->formRow($lof->get(LoseOpportunityForm::CLOSEDATE)); ?>
		<?php echo $this->formRow($lof->get(LoseOpportunityForm::DESCRIPTION)); ?>
		<div class="button-container">
			<?php echo $this->formRow($lof->get(LoseOpportunityForm::SUBMIT)); ?>
			<a id="closeLoseOpportunityButton" class="button lfloat" href="#" title="Cancel">Cancel</a>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>
