<?php

/**
 * Casales Library
 * PHP version 5.4
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * KAATERSKIL MANAGEMENT, LLC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category Casales
 * @package Application
 * @copyright Copyright (c) 2009-2013 Kaaterskil Management, LLC
 * @version SVN $Id: edit.phtml 13 2013-08-05 22:53:55Z  $
 */
use Application\Form\AccountForm;
use Application\Form\AccountFieldset;
use Application\Form\AddressFieldset;
use Application\Form\TelephoneFieldset;

use Zend\Form\Fieldset;

/* @var $form AccountForm */
/* @var $afs AccountFieldset */
/* @var $fieldset Fieldset */

// Set page title
$this->headTitle()->append($this->pageTitle);
$this->headTitle()->append('Casales');

$form = $this->form;
$form->setAttributes(array(
	'action' => $this->url('account', array('action' => 'edit', 'id' => $this->id)),
	'method' => 'post',
	'name' => 'account-edit',
));
$form->prepare();

// Other variables
$afs = $form->get(AccountFieldset::FIELDSETNAME);

$openActivityIndexParams = array(
	'openActivities' => $this->openActivities,
	'entityId' => $this->id,
	'entityRoute' => 'account',
);
$closedActivityIndexParams = array(
	'closedActivities' => $this->closedActivities,
	'entityId' => $this->id,
	'entityRoute' => 'account',
);
$contactIndexParams = array(
	'contacts' => $this->contacts,
	'entityId' => $this->id,
	'entityRoute' => 'account',
);
$auditIndexParams = array(
	'auditItems' => $this->auditItems
);
?>
<div class="grid_12">
	<div class="entity-type">Account</div>
	<h1 class="page-title">
		<?php echo $this->pageTitle; ?>
	</h1>
	
	<ul class="tabs">
		<li><a href="#" id="tab-1" title="tab-content-1" class="tab<?php echo ($this->front == 'tab-1' ? ' front' : ''); ?>">General</a></li>
		<li><a href="#" id="tab-2" title="tab-content-2" class="tab<?php echo ($this->front == 'tab-2' ? ' front' : ''); ?>">Details</a></li>
		<li><a href="#" id="tab-3" title="tab-content-3" class="tab<?php echo ($this->front == 'tab-3' ? ' front' : ''); ?>">Contacts</a></li>
		<li><a href="#" id="tab-4" title="tab-content-4" class="tab<?php echo ($this->front == 'tab-4' ? ' front' : ''); ?>">Open Activities</a></li>
		<li><a href="#" id="tab-5" title="tab-content-5" class="tab<?php echo ($this->front == 'tab-5' ? ' front' : ''); ?>">Closed Activities</a></li>
		<li><a href="#" id="tab-6" title="tab-content-6" class="tab<?php echo ($this->front == 'tab-6' ? ' front' : ''); ?>">Audit</a></li>
	</ul>
	
	<?php echo $this->form()->openTag($form); ?>
	<div id="tab-content-1" class="tab-content">
		<div class="button-container">
			<?php echo $this->formRow($form->get(AccountForm::SUBMIT)); ?>
			<?php echo $this->formRow($form->get(AccountForm::SUBMITCLOSE)); ?>
			<a id="telephoneButton" class="button lfloat mrl mbs" href="#">Add Telephone</a>
			<a id="addressButton"class="button lfloat mrl mbs" href="#">Add Address</a>
		</div>
		<div class="clearfix"></div>
		<?php echo $this->formRow($afs->get(AccountFieldset::ID)); ?>
		<fieldset>
			<legend>General Information</legend>
			<div class="inside-fieldset-left">
				<?php echo $this->formRow($afs->get(AccountFieldset::NAME)); ?>
				<?php echo $this->formRow($afs->get(AccountFieldset::PARENTACCOUNT)); ?>
				<?php echo $this->formRow($afs->get(AccountFieldset::PRIMARYCONTACT)); ?>
			</div>
			<div class="inside-fieldset-right">
				<?php echo $this->formRow($afs->get(AccountFieldset::EMAIL1)); ?>
				<?php echo $this->formRow($afs->get(AccountFieldset::EMAIL2)); ?>
				<?php echo $this->formRow($afs->get(AccountFieldset::WEBSITE)); ?>
			</div>
		</fieldset>
		<div class="clearfix"></div>
		<div class="inner-grid-6 alpha">
			<div id="telephone-container">
				<?php echo $this->formCollection($afs->get(AccountFieldset::TELEPHONES)); ?>
			</div>
		</div>
		<div class="inner-grid-6 omega">
			<div id="address-container">
				<?php echo $this->formCollection($afs->get(AccountFieldset::ADDRESSES)); ?>
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
	
	<div id="tab-content-2" class="tab-content">
		<div class="button-container">
			<?php echo $this->formRow($form->get(AccountForm::SUBMIT)); ?>
			<?php echo $this->formRow($form->get(AccountForm::SUBMITCLOSE)); ?>
		</div>
		<div class="clearfix"></div>
		<fieldset>
			<legend>Relationships</legend>
			<div class="inside-fieldset-left">
			<?php echo $this->formRow($afs->get(AccountFieldset::ORIGINATINGLEAD)); ?>
			<?php echo $this->formRow($afs->get(AccountFieldset::REFERRER)); ?>
			</div>
			<div class="inside-fieldset-right">
			<?php echo $this->formRow($afs->get(AccountFieldset::OWNER)); ?>
			</div>
		</fieldset>
		<div class="clearfix"></div>
		<fieldset>
			<legend>Details</legend>
			<div class="inside-fieldset-left">
				<?php echo $this->formRow($afs->get(AccountFieldset::ACCOUNTTYPE)); ?>
				<?php echo $this->formRow($afs->get(AccountFieldset::ACCOUNTGROUP)); ?>
				<?php echo $this->formRow($afs->get(AccountFieldset::CATEGORY)); ?>
				<?php echo $this->formRow($afs->get(AccountFieldset::SOURCE)); ?>
			</div>
			<div class="inside-fieldset-right">
				<?php echo $this->formRow($afs->get(AccountFieldset::STATE)); ?>
				<?php echo $this->formRow($afs->get(AccountFieldset::DONOTCALL)); ?>
				<?php echo $this->formRow($afs->get(AccountFieldset::DONOTMAIL)); ?>
				<?php echo $this->formRow($afs->get(AccountFieldset::DONOTEMAIL)); ?>
			</div>
		</fieldset>
		<div class="clearfix"></div>
		<fieldset>
			<legend>Notes</legend>
			<?php echo $this->formRow($afs->get(AccountFieldset::DESCRIPTION)); ?>
		</fieldset>
	</div>
	<?php echo $this->form()->closeTag(); ?>
	
	<div id="tab-content-3" class="tab-content">
	<?php echo $this->partial('application/contact/associationContactIndex.phtml', $contactIndexParams); ?>
	</div>
	
	<div id="tab-content-4" class="tab-content">
	<?php echo $this->navigation( $this->navigation )->menu()->renderMenu( null, array('ulClass' => 'ribbon') ); ?>
	<?php echo $this->partial('application/activity/associationOpenActivityIndex.phtml', $openActivityIndexParams); ?>
	</div>
	
	<div id="tab-content-5" class="tab-content">
	<?php echo $this->partial('application/activity/associationClosedActivityIndex.phtml', $closedActivityIndexParams); ?>
	</div>
	
	<div id="tab-content-6" class="tab-content">
	<?php echo $this->partial('application/audit/associationAuditIndex.phtml', $auditIndexParams); ?>
	</div>
</div>
<div class="clearfix"></div>
<div class="grid_12">
	<div class="bottom-status-bar"><?php echo $this->statusMessage; ?></div>
</div>
