<?php

/**
 * Casales Library
 * PHP version 5.4
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * KAATERSKIL MANAGEMENT, LLC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category Casales
 * @package Application
 * @copyright Copyright (c) 2009-2013 Kaaterskil Management, LLC
 * @version SVN $Id: queryForm.phtml 13 2013-08-05 22:53:55Z  $
 */
use Application\Form\AccountFieldset;
use Application\Form\AccountForm;
use Zend\Form\Form;

/* @var $form AccountForm */
/* @var $afs AccountFieldset */

$form = $this->form;
$form->setAttributes( array(
	'action' => $this->url( 'account', array(
		'action' => 'index'
	) ),
	'method' => 'post',
	'name' => 'account-query'
) );
$form->prepare();

$afs = $form->get( AccountFieldset::FIELDSETNAME );
$form->get( AccountForm::SUBMIT )->setAttributes( array(
	'class' => 'button mtm',
	'value' => 'Find'
) );
?>

<div class="query-container">
	<ul class="tabs">
		<li><a href="#" id="tab-1" title="tab-content-1" class="tab front">Find</a></li>
	</ul>

	<div class="tabbed-query-content">
		<?php echo $this->form()->openTag($form); ?>
		<?php echo $this->formRow($afs->get(AccountFieldset::NAME)); ?>
		<?php echo $this->formRow($afs->get(AccountFieldset::ACCOUNTGROUP)); ?>
		<?php echo $this->formRow($form->get(AccountForm::SUBMIT)); ?>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>