<?php

/**
 * Casales Library
 * PHP version 5.4
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * KAATERSKIL MANAGEMENT, LLC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category Casales
 * @package Application
 * @copyright Copyright (c) 2009-2013 Kaaterskil Management, LLC
 * @version SVN $Id: attachmentIndex.phtml 13 2013-08-05 22:53:55Z  $
 */
use Application\Model\SalesLiteratureItem;

/* @var $item SalesLiteratureItem */
?>
<h2>Sales Attachments</h2>
<div class="tabbed-table-container-3">
	<table>
		<thead class="fixed-thead">
			<tr>
				<th width="70"></th>
				<th width="400">Title</th>
				<th width="443">Modified</th>
			</tr>
		</thead>
		<tbody class="scrollable-tbody">
			<?php if(count($this->attachments)) : ?>
			<?php foreach ($this->attachments as $item) : ?>
			<tr>
				<td width="70" align="center"><a
					href="<?php echo $this->url('salesLiterature', array('action' => 'editItem', 'id' => $this->id, 'itemId' => $item->getId())); ?>">Edit</a> <a
					href="<?php echo $this->url('salesLiterature', array('action' => 'deleteItem', 'id' => $this->id, 'itemId' => $item->getId())); ?>">Delete</a></td>
				<td width="400"><?php echo $item->getTitle(); ?></td>
				<td width="417"><?php echo $item->getLastUpdateDate()->format('m/d/Y G:i:s'); ?></td>
			</tr>
			<?php endforeach; ?>
			<?php else : ?>
			<tr>
				<td colspan="3" class="tabbed-no-records">No records found.</td>
			</tr>
			<?php endif; ?>
		</tbody>
	</table>
</div>
