<?php

/**
 * Casales Library
 * PHP version 5.4
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * KAATERSKIL MANAGEMENT, LLC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category Casales
 * @package Application
 * @copyright Copyright (c) 2009-2013 Kaaterskil Management, LLC
 * @version SVN $Id: createItem.phtml 13 2013-08-05 22:53:55Z  $
 */
use Application\Form\SalesLiteratureItemForm;
use Application\Form\SalesLiteratureItemFieldset;

/* @var $sliForm SalesLiteratureItemForm */
/* @var $slifs SalesLiteratureItemFieldset */

// Set page title
$this->headTitle()->append($this->pageTitle);
$this->headTitle()->append('Casales');

$sliForm = $this->form;
$sliForm->setAttributes(array(
	'action' => $this->url('salesLiterature', array('action' => 'createItem', 'id'=> $this->id)),
	'method' => 'post',
	'name' => 'literature-item-create',
));
$sliForm->prepare();

$slifs = $sliForm->get(SalesLiteratureItemFieldset::FIELDSETNAME);
?>
<div class="grid_12">
	<div class="entity-type">Sales Literature Attachment</div>
	<h1 class="page-title">
		<?php echo $this->pageTitle; ?>
	</h1>

	<ul class="tabs">
		<li><a href="#" id="tab-1" title="tab-content-1" class="tab front">General</a></li>
	</ul>
	
	<?php echo $this->form()->openTag($sliForm); ?>
	<div id="tab-content-1" class="tab-content">
		<div class="button-container">
			<?php echo $this->formRow($sliForm->get(SalesLiteratureItemForm::SUBMIT)); ?>
		</div>
		<div class="clearfix"></div>
		<fieldset>
			<legend>General</legend>
			<?php echo $this->formRow($slifs->get(SalesLiteratureItemFieldset::TITLE)); ?>
			<?php echo $this->formRow($slifs->get(SalesLiteratureItemFieldset::AUTHOR)); ?>
			<?php echo $this->formRow($slifs->get(SalesLiteratureItemFieldset::KEYWORDS)); ?>
			<div class="clearfix"></div>
		</fieldset>
		<div class="clearfix"></div>
		<fieldset>
			<legend>Abstract</legend>
			<?php echo $this->formRow($slifs->get(SalesLiteratureItemFieldset::SUMMARY)); ?>
		</fieldset>
		<fieldset>
			<legend>File Attachment</legend>
			<?php echo $this->formRow($slifs->get(SalesLiteratureItemFieldset::FILEUPLOAD)); ?>
		</fieldset>
		<div class="clearfix"></div>
	</div>
	<?php echo $this->form()->closeTag(); ?>
</div>
<div class="clearfix"></div>
<div class="grid_12">
	<div class="bottom-status-bar"><?php echo $this->statusMessage; ?></div>
</div>
