<?php

/**
 * Casales Library
 * PHP version 5.4
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * KAATERSKIL MANAGEMENT, LLC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category Casales
 * @package Application
 * @copyright Copyright (c) 2009-2013 Kaaterskil Management, LLC
 * @version SVN $Id: edit.phtml 13 2013-08-05 22:53:55Z  $
 */
use Application\Form\SalesLiteratureForm;
use Application\Form\SalesLiteratureFieldset;

/* @var $form SalesLiteratureForm */
/* @var $slfs SalesLiteratureFieldset */

// Set page title
$this->headTitle()->append($this->pageTitle);
$this->headTitle()->append('Casales');

$form = $this->form;
$form->setAttributes(array(
	'action' => $this->url('salesLiterature', array('action' => 'edit', 'id' => $this->id)),
	'method' => 'post',
	'name' => 'literature-edit',
));
$form->prepare();

$slfs = $form->get(SalesLiteratureFieldset::FIELDSETNAME);
$attachmentIndexParams = array(
	'attachments' => $this->attachments,
	'id' => $this->id,
);
?>
<div class="grid_12">
	<div class="entity-type">Sales Literature</div>
	<h1 class="page-title">
		<?php echo $this->pageTitle; ?>
	</h1>

	<ul class="tabs">
		<li><a href="#" id="tab-1" title="tab-content-1" class="tab<?php echo ($this->front == 'tab-1' ? ' front' : ''); ?>">General</a></li>
		<li><a href="#" id="tab-2" title="tab-content-2" class="tab<?php echo ($this->front == 'tab-2' ? ' front' : ''); ?>">Attachments</a></li>
	</ul>
	
	<?php echo $this->form()->openTag($form); ?>
	<div id="tab-content-1" class="tab-content">
		<div class="button-container">
			<?php echo $this->formRow($form->get(SalesLiteratureForm::SUBMIT)); ?>
			<?php echo $this->formRow($form->get(SalesLiteratureForm::SUBMITCLOSE)); ?>
		</div>
		<div class="clearfix"></div>
		<fieldset>
			<legend>General</legend>
				<?php echo $this->formRow($slfs->get(SalesLiteratureFieldset::ID)); ?>
				<?php echo $this->formRow($slfs->get(SalesLiteratureFieldset::NAME)); ?>
			<div class="inside-fieldset-left">
				<?php echo $this->formRow($slfs->get(SalesLiteratureFieldset::LITERATURETYPE)); ?>
				<?php echo $this->formRow($slfs->get(SalesLiteratureFieldset::EXPIRATIONDATE)); ?>
			</div>
			<div class="inside-fieldset-right">
				<?php echo $this->formRow($slfs->get(SalesLiteratureFieldset::OWNER)); ?>
			</div>
			<div class="clearfix"></div>
		</fieldset>
		<div class="clearfix"></div>
		<fieldset>
			<legend>Description</legend>
			<?php echo $this->formRow($slfs->get(SalesLiteratureFieldset::DESCRIPTION)); ?>
		</fieldset>
		<div class="clearfix"></div>
	</div>
	<?php echo $this->form()->closeTag(); ?>

	<div id="tab-content-2" class="tab-content">
		<div class="button-container">
			<a id="newLiteratureItemButton" class="button lfloat mll"
				href="<?php echo $this->url('salesLiterature', array('action' => 'createItem', 'id' => $this->id)); ?>">Add Attachment</a>
		</div>
		<div class="clearfix"></div>
		<?php echo $this->partial('application/salesLiterature/attachmentIndex.phtml', $attachmentIndexParams); ?>
	</div>
</div>
<div class="clearfix"></div>
<div class="grid_12">
	<div class="bottom-status-bar"><?php echo $this->statusMessage; ?></div>
</div>
