<?php

/**
 * Casales Library
 * PHP version 5.4
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * KAATERSKIL MANAGEMENT, LLC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category Casales
 * @package Application
 * @copyright Copyright (c) 2009-2013 Kaaterskil Management, LLC
 * @version SVN $Id: edit.phtml 13 2013-08-05 22:53:55Z  $
 */
use Application\Form\LeadForm;
use Application\Form\LeadFieldset;
use Application\Form\AddressFieldset;
use Application\Form\TelephoneFieldset;

use Zend\Form\Fieldset;

/* @var $form LeadForm */
/* @var $qlf QualifyLeadForm */
/* @var $lfs LeadFieldset */
/* @var $fieldset Fieldset */

// Set page title
$this->headTitle()->append($this->pageTitle);
$this->headTitle()->append('Casales');

$form = $this->form;
$form->setAttributes(array(
	'action' => $this->url('lead', array('action' => 'edit', 'id' => $this->id)),
	'method' => 'post',
	'name' => 'lead-edit',
));
$form->prepare();

// Other variables
$lfs = $form->get(LeadFieldset::FIELDSETNAME);
$activityIndexParams = array(
	'openActivities' => $this->openActivities,
	'closedActivities' => $this->closedActivities,
	'entityId' => $this->id,
	'entityRoute' => 'lead',
);
$qualifyLeadParams = array(
	'qualifyLeadForm' => $this->qualifyLeadForm,
	'id' => $this->id,
);
$auditIndexParams = array(
	'auditItems' => $this->auditItems
);
?>
<div class="grid_12">
	<div class="entity-type">Lead</div>
	<h1 class="page-title">
		<?php echo $this->pageTitle; ?>
	</h1>

	<ul class="tabs">
		<li><a href="#" id="tab-1" title="tab-content-1" class="tab front">General</a></li>
		<li><a href="#" id="tab-2" title="tab-content-2" class="tab">Details</a></li>
		<li><a href="#" id="tab-3" title="tab-content-3" class="tab">Activities</a></li>
		<li><a href="#" id="tab-5" title="tab-content-5" class="tab">Audit</a></li>
	</ul>
	
	<?php echo $this->form()->openTag($form); ?>
	<div id="tab-content-1" class="tab-content">
		<div class="button-container">
			<div class="lfloat mbm">
				<?php echo $this->formRow($form->get(LeadForm::SUBMIT)); ?>
			</div>
			<?php echo $this->formRow($form->get(LeadForm::SUBMITCLOSE)); ?>
			<a id="telephoneButton" class="button lfloat mll" href="#">Add Telephone</a>
			<a id="addressButton" class="button lfloat mll" href="#">Add Address</a>
			<?php if($this->showQualifyLeadButton) : ?>
			<a id="openQualifyLeadButton" class="button lfloat mll" href="#">Qualify Lead</a>
			<?php endif; ?>
		</div>
		<div class="clearfix"></div>
		<?php echo $this->formRow($lfs->get(LeadFieldset::ID)); ?>
		<fieldset>
			<legend>Personal Information</legend>
			<div class="inside-fieldset-left">
				<?php echo $this->formRow($lfs->get(LeadFieldset::SALUTATION)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::PREFIX)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::FIRSTNAME)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::MIDDLENAME)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::LASTNAME)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::SUFFIX)); ?>
			</div>
			<div class="inside-fieldset-right">
				<?php echo $this->formRow($lfs->get(LeadFieldset::COMPANYNAME)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::WEBSITE)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::JOBTITLE)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::EMAIL1)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::EMAIL2)); ?>
			</div>
		</fieldset>
		<div class="clearfix"></div>
		<div class="inner-grid-6 alpha">
			<div id="telephone-container">
			<?php echo $this->formCollection($lfs->get(LeadFieldset::TELEPHONE)); ?>
			</div>
		</div>
		<div class="inner-grid-6 omega">
			<div id="address-container">
				<?php echo $this->formCollection($lfs->get(LeadFieldset::ADDRESS)); ?>
			</div>
		</div>
		<div class="clearfix"></div>
	</div>

	<div id="tab-content-2" class="tab-content">
		<fieldset>
			<legend>General</legend>
			<div class="inside-fieldset-left">
			<?php echo $this->formRow($lfs->get(LeadFieldset::ACCOUNT)); ?>
			<?php echo $this->formRow($lfs->get(LeadFieldset::CONTACT)); ?>
			<?php echo $this->formRow($lfs->get(LeadFieldset::OPPORTUNITY)); ?>
			</div>
			<div class="inside-fieldset-right">
			<?php echo $this->formRow($lfs->get(LeadFieldset::OWNER)); ?>
			</div>
		</fieldset>
		<div class="clearfix"></div>
		<fieldset>
			<legend>Status</legend>
			<div class="inside-fieldset-left">
				<?php echo $this->formRow($lfs->get(LeadFieldset::DECISIONMAKER)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::PURCHASEPROCESS)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::NEED)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::PURCHASETIMEFRAME)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::CONFIRMINTEREST)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::EVALUATEFIT)); ?>
			</div>
			<div class="inside-fieldset-right">
				<?php echo $this->formRow($lfs->get(LeadFieldset::STATUS)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::PRIORITY)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::LEADSOURCE)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::LEADQUALITY)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::INITIALCONTACT)); ?>
			</div>
		</fieldset>
		<div class="inner-grid-6 alpha">
			<fieldset>
				<legend>Potential</legend>
				<?php echo $this->formRow($lfs->get(LeadFieldset::ESTIMATEDVALUE)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::REVENUE)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::ESTIMATEDCLOSEDATE)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::SCHEDULEFOLLOWUPPROSPECT)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::SCHEDULEFOLLOWUPQUALIFY)); ?>
			</fieldset>
		</div>
		<div class="inner-grid-6 omega">
			<fieldset>
				<legend>Warnings</legend>
				<?php echo $this->formRow($lfs->get(LeadFieldset::DONOTPHONE)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::DONOTMAIL)); ?>
				<?php echo $this->formRow($lfs->get(LeadFieldset::DONOTEMAIL)); ?>
			</fieldset>
		</div>

		<div class="clearfix"></div>
		<?php echo $this->formRow($lfs->get(LeadFieldset::DESCRIPTION)); ?>
		<?php echo $this->formRow($lfs->get(LeadFieldset::QUALIFICATIONCOMMENTS)); ?>
	</div>
	<?php echo $this->form()->closeTag(); ?>
		
	<div id="tab-content-3" class="tab-content">
	<?php echo $this->navigation( $this->navigation )->menu()->renderMenu( null, array('ulClass' => 'ribbon') ); ?>
	<?php echo $this->partial('application/activity/associationActivityIndex.phtml', $activityIndexParams); ?>
	</div>
	
	<div id="tab-content-5" class="tab-content">
	<?php echo $this->partial('application/audit/associationAuditIndex.phtml', $auditIndexParams); ?>
	</div>

	<div id="qualify-lead-container" class="<?php echo $this->qualifyLeadContainerClass; ?>">
	<?php echo $this->partial('application/lead/qualifyLead.phtml', $qualifyLeadParams); ?>
	</div>
</div>
<div class="clearfix"></div>
<div class="grid_12">
	<div class="bottom-status-bar"><?php echo $this->statusMessage; ?></div>
</div>
