<?php

/**
 * Casales Library
 * PHP version 5.4
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * KAATERSKIL MANAGEMENT, LLC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category Casales
 * @package Application
 * @copyright Copyright (c) 2009-2013 Kaaterskil Management, LLC
 * @version SVN $Id: edit.phtml 13 2013-08-05 22:53:55Z  $
 */
use Application\Form\BusinessUnitForm;
use Application\Form\BusinessUnitFieldset;

/* @var $form BusinessUnitForm */
/* @var $bufs BusinessUnitFieldset */

// Set page title
$this->headTitle()->append($this->pageTitle);
$this->headTitle()->append('Casales');

$form = $this->form;
$form->setAttributes(array(
	'action' => $this->url('businessUnit', array('action' => 'edit', 'id' => $this->id)),
	'method' => 'post',
	'name' => 'business-unit-edit',
));
$form->prepare();

$bufs = $form->get(BusinessUnitFieldset::FIELDSETNAME);

$auditIndexParams = array(
	'auditItems' => $this->auditItems
);
$userIndexParams = array(
	'users' => $this->users
);
?>
<div class="grid_12">
	<div class="entity-type">Business Unit</div>
	<h1 class="page-title">
		<?php echo $this->pageTitle; ?>
	</h1>
	
	<ul class="tabs">
		<li><a href="#" id="tab-1" title="tab-content-1" class="tab front">General</a></li>
		<li><a href="#" id="tab-2" title="tab-content-2" class="tab">Users</a></li>
		<li><a href="#" id="tab-3" title="tab-content-3" class="tab">Audit</a></li>
	</ul>
	
	<div id="tab-content-1" class="tab-content">
		<?php echo $this->form()->openTag($form); ?>
		<div class="button-container">
			<?php echo $this->formRow($form->get(BusinessUnitForm::SUBMIT)); ?>
			<?php echo $this->formRow($form->get(BusinessUnitForm::SUBMITCLOSE)); ?>
		</div>
		<div class="clearfix"></div>
		<fieldset>
			<legend>General</legend>
			<div class="inside-fieldset-left">
				<?php echo $this->formRow($bufs->get(BusinessUnitFieldset::ID)); ?>
				<?php echo $this->formRow($bufs->get(BusinessUnitFieldset::NAME)); ?>
				<?php echo $this->formRow($bufs->get(BusinessUnitFieldset::PARENTBUSINESSUNIT)); ?>
				<?php echo $this->formRow($bufs->get(BusinessUnitFieldset::DIVISIONNAME)); ?>
				<?php echo $this->formRow($bufs->get(BusinessUnitFieldset::COSTCENTER)); ?>
			</div>
			<div class="inside-fieldset-right">
				<?php echo $this->formRow($bufs->get(BusinessUnitFieldset::EMAIL)); ?>
				<?php echo $this->formRow($bufs->get(BusinessUnitFieldset::WEBSITE)); ?>
				<?php echo $this->formRow($bufs->get(BusinessUnitFieldset::ISDISABLED)); ?>
				<?php echo $this->formRow($bufs->get(BusinessUnitFieldset::DISABLEDREASON)); ?>
			</div>
		</fieldset>
		<fieldset>
			<legend>Notes</legend>
			<?php echo $this->formRow($bufs->get(BusinessUnitFieldset::DESCRIPTION)); ?>
		</fieldset>
		<div class="clearfix"></div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
	
	<div id="tab-content-2" class="tab-content">
	<?php echo $this->partial('application/user/associationUserIndex.phtml', $userIndexParams); ?>
	</div>
	
	<div id="tab-content-3" class="tab-content">
	<?php echo $this->partial('application/audit/associationAuditIndex.phtml', $auditIndexParams); ?>
	</div>
</div>
<div class="clearfix"></div>
<div class="grid_12">
	<div class="bottom-status-bar"><?php echo $this->statusMessage; ?></div>
</div>
