<?php

/**
 * Casales Library
 * PHP version 5.4
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * KAATERSKIL MANAGEMENT, LLC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category Casales
 * @package Application
 * @copyright Copyright (c) 2009-2013 Kaaterskil Management, LLC
 * @version SVN $Id: associationActivityIndex.phtml 13 2013-08-05 22:53:55Z  $
 */
use Application\Model\AbstractActivity;
use Application\Model\Schedulable;
use Application\Model\StatefulActivity;
use Application\Model\Trackable;

/* @var $activity AbstractActivity */
/* @var $sta StatefulActivity */
/* @var $sch Schedulable */
/* @var $trk Trackable */
?>
<h2>Open Activities</h2>
<div class="tabbed-table-container">
	<table>
		<thead class="fixed-thead">
			<tr>
				<th width="300" class="first">Subject</th>
				<th width="120">Type</th>
				<th width="80">Status</th>
				<th width="180">Regarding</th>
				<th width="100">Priority</th>
				<th width="133">Start Date</th>
			</tr>
		</thead>
		<tbody class="scrollable-tbody">
			<?php if(count($this->openActivities)) : ?>
			<?php foreach ($this->openActivities as $activity) : ?>
			<?php
			$state = '';
			$priority = '';
			$scheduledEnd = '';
			$scheduledStart = '';
			if ($activity instanceof StatefulActivity) {
				$sta = $activity;
				$state = $sta->getStatus();
				$priority = $sta->getPriority();
			}
			if ($activity instanceof Schedulable) {
				$sch = $activity;
				$scheduledEnd = $sch->getFormattedScheduledEnd();
				$scheduledStart = $sch->getFormattedScheduledStart();
			}
			$link = $this->url( 'activity', array(
				'action' => 'edit',
				'id' => $activity->getId(),
				'type' => $activity->getDiscriminator(),
				'entityId' => $this->entityId,
				'entityRoute' => $this->entityRoute
			) );
			?>
			<tr>
				<td width="300" class="first"><a href="<?php echo $link; ?>"><?php echo $activity->getSubject(); ?></a></td>
				<td width="120"><?php echo $activity->getDiscriminatorTitle(); ?></td>
				<td width="80"><?php echo $state; ?></td>
				<td width="180"><?php echo $activity->getRegardingObjectName(true); ?></td>
				<td width="100"><?php echo $priority; ?></td>
				<td width="117"><?php echo $scheduledStart; ?></td>
			</tr>
			<?php endforeach; ?>
			<?php else : ?>
			<tr>
				<td colspan="6" class="tabbed-no-records">No records found.</td>
			</tr>
			<?php endif; ?>
		</tbody>
	</table>
</div>
<h2>Closed Activities</h2>
<div class="tabbed-table-container">
	<table>
		<thead class="fixed-thead">
			<tr>
				<th width="300" class="first">Subject</th>
				<th width="120">Type</th>
				<th width="80">Status</th>
				<th width="180">Regarding</th>
				<th width="100">Priority</th>
				<th width="133">End Date</th>
			</tr>
		</thead>
		<tbody class="scrollable-tbody">
			<?php if (count($this->closedActivities)) : ?>
			<?php foreach ($this->closedActivities as $activity) : ?>
			<?php
			$status = '';
			$priority = '';
			$actualEnd = '';
			$actualStart = '';
			if ($activity instanceof StatefulActivity) {
				$sta = $activity;
				$status = $sta->getStatus();
				$priority = $sta->getPriority();
			}
			if ($activity instanceof Trackable) {
				$trk = $activity;
				$actualEnd = $trk->getFormattedActualEnd();
				$actualStart = $trk->getFormattedActualStart();
			}
			$link = $this->url( 'activity', array(
				'action' => 'edit',
				'id' => $activity->getId(),
				'type' => $activity->getDiscriminator(),
				'entityId' => $this->entityId,
				'entityRoute' => $this->entityRoute
			) );
			?>
			<tr>
				<td width="300" class="first"><a href="<?php echo $link; ?>"><?php echo $activity->getSubject(); ?></a></td>
				<td width="120"><?php echo $activity->getDiscriminatorTitle(); ?></td>
				<td width="80"><?php echo $status; ?></td>
				<td width="180"><?php echo $activity->getRegardingObjectName(true); ?></td>
				<td width="100"><?php echo $priority; ?></td>
				<td width="117"><?php echo $actualEnd; ?></td>
			</tr>
			<?php endforeach; ?>
			<?php else : ?>
			<tr>
				<td colspan="6" class="tabbed-no-records">No records found.</td>
			</tr>
			<?php endif;?>
		</tbody>
	</table>
</div>