<?php

/**
 * Casales Library
 * PHP version 5.4
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * KAATERSKIL MANAGEMENT, LLC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category Casales
 * @package Application
 * @copyright Copyright (c) 2009-2013 Kaaterskil Management, LLC
 * @version SVN $Id: createResponse.phtml 13 2013-08-05 22:53:55Z  $
 */
use Application\Form\ActivityForm;
use Application\Form\BaseActivityFieldset;
use Application\Form\CampaignResponseFieldset;

/* @var $form ActivityForm */
/* @var $crfs CampaignResponseFieldset */

// Set page title
$this->headTitle()->append($this->pageTitle);
$this->headTitle()->append('Casales');

$form = $this->form;

// Set the form attributes
$form->setAttributes(array(
	'action' => $this->url('activity', array(
		'action' => 'promoteToResponse',
		'id' => $this->id,
		'type' => $this->type,
		'entityId' => $this->entityId,
		'entityRoute' => $this->entityRoute
	)),
	'method' => 'post',
	'name' => 'activity-create',
));
$form->prepare();

// Get the fieldset
$crfs = $form->get(BaseActivityFieldset::FIELDSETNAME);
$crfs->get(BaseActivityFieldset::SUBJECT)->setAttribute('size', 130);
$crfs->get(BaseActivityFieldset::DESCRIPTION)->setAttributes(array(
	'class' => 'input-text mtt',
	'cols' => 174,
	'rows' => 17
));
?>
<div class="grid_12">
	<div class="entity-type">Campaign Response</div>
	<h1 class="page-title">
		<?php echo $this->pageTitle; ?>
	</h1>

	<div class="tab-content">
		<?php echo $this->form()->openTag($form); ?>
		<div class="button-container mbl">
		<?php echo $this->formRow($form->get(ActivityForm::SUBMITCLOSE)); ?>
		</div>
		<?php
		echo $this->formRow($crfs->get(BaseActivityFieldset::DISCRIMINATOR));
		echo $this->formRow($crfs->get(BaseActivityFieldset::ACCOUNT));
		echo $this->formRow($crfs->get(BaseActivityFieldset::CAMPAIGN));
		echo $this->formRow($crfs->get(BaseActivityFieldset::CONTACT));
		echo $this->formRow($crfs->get(BaseActivityFieldset::LEAD));
		echo $this->formRow($crfs->get(BaseActivityFieldset::OPPORTUNITY));
		?>
		<div>
		<?php
		echo $this->formRow($crfs->get(BaseActivityFieldset::SUBJECT));
		echo $this->formElement($crfs->get(BaseActivityFieldset::DESCRIPTION));
		?>
		</div>
		<fieldset>
			<legend>Received From</legend>
			<?php echo $this->formRow($crfs->get(CampaignResponseFieldset::FROM)); ?>
		</fieldset>
		<fieldset>
			<legend>Details</legend>
			<?php echo $this->formRow($crfs->get(CampaignResponseFieldset::CAMPAIGNACTIVITY)); ?>
			<div class="inside-fieldset-left">
			<?php
			echo $this->formRow($crfs->get(CampaignResponseFieldset::CHANNEL));
			echo $this->formRow($crfs->get(CampaignResponseFieldset::RESPONSECODE));
			echo $this->formRow($crfs->get(CampaignResponseFieldset::RECEIVEDON));
			echo $this->formRow($crfs->get(CampaignResponseFieldset::SCHEDULEDEND));
			?>
			</div>
			<div class="inside-fieldset-right">
			<?php
			echo $this->formRow($crfs->get(BaseActivityFieldset::OWNER));
			echo $this->formRow($crfs->get(CampaignResponseFieldset::PRIORITY));
			echo $this->formRow($crfs->get(CampaignResponseFieldset::STATUS));
			?>
			</div>
		</fieldset>
		<div class="clearfix"></div>
	<?php echo $this->form()->closeTag(); ?>
	</div>
</div>
<div class="clearfix"></div>
<div class="grid_12">
	<div class="bottom-status-bar"><?php echo $this->statusMessage; ?></div>
</div>
