<?php

/**
 * Casales Library
 * PHP version 5.4
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * KAATERSKIL MANAGEMENT, LLC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category Casales
 * @package Application
 * @copyright Copyright (c) 2009-2013 Kaaterskil Management, LLC
 * @version SVN $Id: createReplyEmail.phtml 13 2013-08-05 22:53:55Z  $
 */
use Application\Form\ActivityForm;
use Application\Form\BaseActivityFieldset;
use Application\Form\CampaignActivityFieldset;
use Application\Form\AppointmentFieldset;
use Application\Form\TaskFieldset;
use Application\Form\NoteFieldset;
use Application\Form\InteractionFieldset;
use Application\Form\FaxFieldset;
use Application\Form\LetterFieldset;
use Application\Form\TelephoneInteractionFieldset;
use Application\Form\VisitFieldset;
use Application\Model\LetterInteraction;
use Application\Form\EmailFieldset;

/* @var $form ActivityForm */
/* @var $afs BaseActivityFieldset */

// Set page title
$this->headTitle()->append($this->pageTitle);
$this->headTitle()->append('Casales');

$form = $this->form;

// Set the form attributes
$form->setAttributes(array(
	'action' => $this->url('mail', array(
		'action' => 'reply',
		'id' => $this->id,
	)),
	'method' => 'post',
	'name' => 'mail-reply',
));
$form->prepare();

// Get the fieldset
$afs = $form->get(BaseActivityFieldset::FIELDSETNAME);
$form->get(ActivityForm::SUBMITCLOSE)->setAttribute('class', 'button mll mbl');
?>
<div class="grid_12">
	<div class="entity-type">Mail</div>
	<h1 class="page-title">
		<?php echo $this->pageTitle; ?>
	</h1>

	<div class="tab-content">
		<?php
		echo $this->form()->openTag($form);
		echo $this->formRow($afs->get(BaseActivityFieldset::DISCRIMINATOR));
		echo $this->formRow($afs->get(BaseActivityFieldset::ACCOUNT));
		echo $this->formRow($afs->get(BaseActivityFieldset::CAMPAIGN));
		echo $this->formRow($afs->get(BaseActivityFieldset::CONTACT));
		echo $this->formRow($afs->get(BaseActivityFieldset::LEAD));
		echo $this->formRow($afs->get(BaseActivityFieldset::OPPORTUNITY));
		echo $this->formRow($afs->get(BaseActivityFieldset::OWNER));
		?>
		<div>
		<?php
		echo $this->formRow($afs->get(EmailFieldset::FROM));
		echo $this->formRow($afs->get(EmailFieldset::TO));
		echo $this->formRow($afs->get(EmailFieldset::CC));
		echo $this->formRow($afs->get(EmailFieldset::BCC));
		echo $this->formRow($afs->get(EmailFieldset::SUBJECT));
		echo $this->formRow($afs->get(EmailFieldset::MESSAGEID));
		?>
		</div>
		<div class="inner-grid-6 alpha">
			<?php echo $this->formRow($afs->get(EmailFieldset::FILEUPLOAD)); ?>
		</div>
		<div class="inner-grid-6 omega">
			<?php echo $this->formRow($afs->get(EmailFieldset::DIRECTION)); ?>
		</div>
		<div class="clearfix"></div>
		<?php echo $this->formElement($afs->get(EmailFieldset::DESCRIPTION)); ?>
		
		<div class="inner-grid-6 alpha">
			<fieldset>
				<legend>Notifications</legend>
				<?php
				echo $this->formRow($afs->get(EmailFieldset::DELIVERYRECEIPTREQUESTED));
				echo $this->formRow($afs->get(EmailFieldset::READRECEIPTREQUESTED));
				?>
			</fieldset>
		</div>
		<div class="inner-grid-6 omega">
			<fieldset>
				<legend>Send Options</legend>
				<?php
				echo $this->formRow($afs->get(EmailFieldset::PRIORITY));
				echo $this->formRow($afs->get(EmailFieldset::STATUS));
				echo $this->formRow($afs->get(EmailFieldset::ISSUESEND));
				echo $this->formRow($form->get(ActivityForm::SUBMITCLOSE));
				?>
			</fieldset>
		</div>
		<div class="clearfix"></div>
	<?php echo $this->form()->closeTag(); ?>
	</div>
</div>
<div class="clearfix"></div>
<div class="grid_12">
	<div class="bottom-status-bar"><?php echo $this->statusMessage; ?></div>
</div>
