<?php

/**
 * Casales Library
 * PHP version 5.4
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * KAATERSKIL MANAGEMENT, LLC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category Casales
 * @package Application
 * @copyright Copyright (c) 2009-2013 Kaaterskil Management, LLC
 * @version SVN $Id: listQuery.phtml 13 2013-08-05 22:53:55Z  $
 */
use Application\Form\MarketingListFieldset;
use Application\Form\MarketingListForm;
use Zend\Form\Fieldset;
use Zend\Form\Form;

$queryForm = $this->queryForm;
$queryForm->setAttributes(array(
	'action' => $this->url('activity', array(
			'action' => 'marketingListIndex',
			'id' => $this->id,
			'type' => 'Query',
			'entityId' => $this->entityId,
			'entityRoute' => $this->entityRoute
		)),
	'method' => 'post',
	'name' => 'campaignActivity-list-query'
));
$queryForm->get( MarketingListForm::SUBMIT )->setValue( 'Find' );
$queryForm->prepare();

$fs = $queryForm->get( MarketingListFieldset::FIELDSETNAME );

$indexParams = array(
	'entityId' => $this->entityId,
	'entityRoute' => $this->entityRoute,
	'id' => $this->id,
	'recordSet' => $this->recordSet,
);
?>

<h2>Marketing Lists</h2>
<div class="">
	<?php echo $this->form()->openTag($queryForm); ?>
	<?php echo $this->formRow($fs->get(MarketingListFieldset::NAME)); ?>
	<?php echo $this->formRow($fs->get(MarketingListFieldset::SOURCE)); ?>
	<div class="mts">
		<?php echo $this->formRow($queryForm->get(MarketingListForm::SUBMIT)); ?>
	</div>
	<?php echo $this->form()->closeTag(); ?>
</div>
<div class="clearfix"></div>
<div class="">
	<?php echo $this->partial('application/activity/listQueryIndex.phtml', $indexParams); ?>
</div>
