<?php

/**
 * Casales Library
 * PHP version 5.4
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * KAATERSKIL MANAGEMENT, LLC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category Casales
 * @package Application
 * @copyright Copyright (c) 2009-2013 Kaaterskil Management, LLC
 * @version SVN $Id: create.phtml 13 2013-08-05 22:53:55Z  $
 */
use Application\Form\AccountGroupForm;
use Application\Form\AccountGroupFieldset;

/* @var $form AccountGroupForm */
/* @var $agf AccountGroupFieldset */

// Set page title
$this->headTitle()->append($this->pageTitle);
$this->headTitle()->append('Casales');

$form = $this->form;

// Set the form attributes
$form->setAttributes(array(
	'action' => $this->url('group', array('action' => 'create', 'id' => 0)),
	'method' => 'post',
	'name' => 'group-create',
));

// Prepare the form elements
$form->prepare();

// Get the fieldset
$agf = $form->get(AccountGroupFieldset::FIELDSETNAME);
?>
<div class="grid_12">
	<h1 class="page-title">
		<?php echo $this->pageTitle; ?>
	</h1>
	<?php echo $this->form()->openTag($form); ?>
	<?php echo $this->formRow($agf->get(AccountGroupFieldset::PARENTGROUP)); ?>
	<?php echo $this->formRow($agf->get(AccountGroupFieldset::DESCRIPTION)); ?>
	<?php echo $this->formRow($form->get(AccountGroupForm::SUBMIT)); ?>
	<?php echo $this->form()->closeTag(); ?>
</div>
