<?php

/**
 * Casales Library
 * PHP version 5.4
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * KAATERSKIL MANAGEMENT, LLC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category Casales
 * @package Application
 * @copyright Copyright (c) 2009-2013 Kaaterskil Management, LLC
 * @version SVN $Id: index.phtml 13 2013-08-05 22:53:55Z  $
 */
use Application\Model\AccountGroup;

/* @var $obj AccountGroup */

// Set page title
$this->headTitle()->append( $this->pageTitle );
$this->headTitle()->append( 'Casales' );
?>
<div class="grid_12">
	<h1 class="page-title">
		<?php echo $this->pageTitle; ?>
	</h1>
	<p>
		<a
			accesskey="n"
			href="<?php echo $this->url('group', array('action' => 'create')); ?>">Create
			New</a>
	</p>
	<div class="table-window">
		<table>
			<thead>
				<tr>
					<td
						width="80"
						align="center"></td>
					<td
						width="40"
						align="center">Id</td>
					<td width="250">Name</td>
					<td width="250">Parent</td>
				</tr>
			</thead>
			<tbody>
				<?php if(count($this->recordSet)) : ?>
				<?php foreach ($this->recordSet as $obj) : ?>
				<?php
				$parent = $obj->getParent() ? $obj->getParent()->getDescription() : '';
				?>
				<tr>
					<td align="center"><a
						href="<?php echo $this->url('group', array('action' => 'edit', 'id' => $obj->getId())); ?>">Edit</a>
						<a
						href="<?php echo $this->url('group', array('action' => 'delete', 'id' => $obj->getId())); ?>">Delete</a>
					</td>
					<td align="center"><?php echo $obj->getId(); ?></td>
					<td><?php echo $obj->getDescription(); ?></td>
					<td><?php echo $parent; ?></td>
				</tr>
				<?php endforeach; ?>
				<?php else : ?>
				<tr>
					<td colspan="4">No records found.</td>
				</tr>
				<?php endif; ?>
			</tbody>
		</table>
	</div>
</div>
