<?php

/**
 * Casales Library
 * PHP version 5.4
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * KAATERSKIL MANAGEMENT, LLC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category Casales
 * @package Application
 * @copyright Copyright (c) 2009-2013 Kaaterskil Management, LLC
 * @version SVN $Id: index.phtml 13 2013-08-05 22:53:55Z  $
 */
use Application\Model\User;

/* @var $obj User */

// Set page title
$this->headTitle()->append( $this->pageTitle );
$this->headTitle()->append( 'Casales' );
?>

<div class="grid_12">
	<div class="entity-type">User</div>
	<h1 class="page-title">
		<?php echo $this->pageTitle; ?>
	</h1>
	<div>
		<a accesskey="n" class="mll" href="<?php echo $this->url('user', array('action' => 'create')); ?>">Create New</a>
	</div>
	<div class="table-container">
		<table class="scrollable-table">
			<thead class="fixed-thead">
				<tr>
					<th width="70"></th>
					<th width="200">Name</th>
					<th width="200">Business Unit</th>
					<th width="90">License</th>
					<th width="90">Access</th>
					<th width="288">Email</th>
				</tr>
			</thead>
			<tbody class="scrollable-tbody">
				<?php if(count($this->recordSet)) : ?>
				<?php foreach ($this->recordSet as $obj) : ?>
				<?php
				$emailLink = '';
				if ($obj->getEmail() != '') {
					$emailLink = '<a href="mailto:' . $obj->getEmail() . '">' . $obj->getEmail() . '</a>';
				}
				?>
				<tr>
					<td width="70" align="center"><a
						href="<?php echo $this->url('user', array('action' => 'edit', 'id' => $obj->getId())); ?>">Edit</a> <a
						href="<?php echo $this->url('user', array('action' => 'delete', 'id' => $obj->getId())); ?>">Delete</a></td>
					<td width="200"><?php echo $obj->getFullName(); ?></td>
					<td width="200"><?php echo ($obj->getBusinessUnit() != null ? $obj->getBusinessUnit()->getName() : ''); ?></td>
					<td width="90"><?php echo $obj->getLicenseType(); ?></td>
					<td width="90"><?php echo $obj->getAccessMode(); ?></td>
					<td width="272"><?php echo $emailLink; ?></td>
				</tr>
				<?php endforeach; ?>
				<?php else : ?>
				<tr>
					<td colspan="6" class="no-records">No records found.</td>
				</tr>
				<?php endif; ?>
				</tbody>
		</table>
	</div>
</div>
<div class="clearfix"></div>
<div class="grid_12">
	<div class="bottom-status-bar"><?php echo $this->statusMessage; ?></div>
</div>
