<?php

/**
 * Casales Library
 * PHP version 5.4
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * KAATERSKIL MANAGEMENT, LLC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category Casales
 * @package Application
 * @copyright Copyright (c) 2009-2013 Kaaterskil Management, LLC
 * @version SVN $Id: create.phtml 13 2013-08-05 22:53:55Z  $
 */
use Application\Form\MarketingListForm;
use Application\Form\MarketingListFieldset;

/* @var $form MarketingListForm */
/* @var $cfs MarketingListFieldset */

// Set page title
$this->headTitle()->append($this->pageTitle);
$this->headTitle()->append('Casales');

$form = $this->form;
$form->setAttributes(array(
	'action' => $this->url('marketingList', array('action' => 'create')),
	'method' => 'post',
	'name' => 'marketing-list-create',
));
$form->prepare();

$cfs = $form->get(MarketingListFieldset::FIELDSETNAME);
?>
<div class="grid_12">
	<div class="entity-type">Marketing List</div>
	<h1 class="page-title">
		<?php echo $this->pageTitle; ?>
	</h1>

	<ul class="tabs">
		<li><a href="#" id="tab-1" title="tab-content-1" class="tab front">General</a></li>
	</ul>
	
	<?php echo $this->form()->openTag($form); ?>
	<div id="tab-content-1" class="tab-content">
		<div class="button-container">
			<?php echo $this->formRow($form->get(MarketingListForm::SUBMIT)); ?>
			<?php echo $this->formRow($form->get(MarketingListForm::SUBMITCLOSE)); ?>
		</div>
		<div class="clearfix"></div>
		<fieldset>
			<legend>General</legend>
			<div class="inside-fieldset-left">
				<?php echo $this->formRow($cfs->get(MarketingListFieldset::NAME)); ?>
				<?php echo $this->formRow($cfs->get(MarketingListFieldset::SOURCE)); ?>
				<?php echo $this->formRow($cfs->get(MarketingListFieldset::LOCKSTATUS)); ?>
			</div>
			<div class="inside-fieldset-right">
				<?php echo $this->formRow($cfs->get(MarketingListFieldset::MEMBERTYPE)); ?>
				<?php echo $this->formRow($cfs->get(MarketingListFieldset::STATUS)); ?>
				<?php echo $this->formRow($cfs->get(MarketingListFieldset::OWNER)); ?>
			</div>
			<div class="clearfix"></div>
			<?php echo $this->formRow($cfs->get(MarketingListFieldset::PURPOSE)); ?>
		</fieldset>
		<div class="clearfix"></div>
		<fieldset>
			<legend>Description</legend>
			<?php echo $this->formRow($cfs->get(MarketingListFieldset::DESCRIPTION)); ?>
		</fieldset>
		<div class="clearfix"></div>
	</div>
	<?php echo $this->form()->closeTag(); ?>
</div>
<div class="clearfix"></div>
<div class="grid_12">
	<div class="bottom-status-bar"><?php echo $this->statusMessage; ?></div>
</div>
