<?php

/**
 * Casales Library
 * PHP version 5.4
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * KAATERSKIL MANAGEMENT, LLC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category Casales
 * @package Application
 * @copyright Copyright (c) 2009-2013 Kaaterskil Management, LLC
 * @version SVN $Id: memberQueryIndex.phtml 13 2013-08-05 22:53:55Z  $
 */
use Application\Model\Account;
use Application\Model\Contact;
use Application\Model\Lead;
use Application\Model\MemberType;

/* @var $account Account */
/* @var $contact Contact */
/* @var $lead Lead */

$recordSet = $this->recordSet;
$rowCount = 0;
?>
<form name="member-query-index-form"
	action="<?php echo $this->url('marketingList', array('action' => 'memberIndex', 'id'=> $this->id, 'type' => 'Add')); ?>"
	method="post">
	<div class="tabbed-table-container-4">
<?php if($this->memberType == MemberType::ACCOUNT) : ?>
		<table>
			<thead class="fixed-thead">
				<tr>
					<th width="40" align="center">Select</th>
					<th width="330">Account Name</th>
					<th width="80">City</th>
					<th width="40">State</th>
					<th width="100">Telephone</th>
					<th width="326">Email</th>
				</tr>
			</thead>
			<tbody class="scrollable-tbody">
	<?php if(count($recordSet)) : ?>
		<?php foreach ($recordSet as $account) : ?>
				<tr class="marketing-list-item">
					<td width="40" align="center">
						<input type="checkbox" id="checkbox_row_<?php echo ++$rowCount; ?>" name="selected_fld[]" value="<?php echo $account->getId(); ?>">
					</td>
					<td width="200"><?php echo $account->getDisplayName(true); ?></td>
					<td width="80"><?php echo $account->getPrimaryAddress()->getCity(); ?></td>
					<td width="40"><?php echo $account->getPrimaryAddress()->getRegion() ?></td>
					<td width="100"><?php echo $account->getPrimaryTelephone(); ?></td>
					<td width="310"><?php echo $account->getEmail1(); ?></td>
				</tr>
		<?php endforeach; ?>
	<?php else : ?>
				<tr>
					<td colspan="6" class="no-records">No records found.</td>
				</tr>
	<?php endif; ?>
			</tbody>
		</table>
<?php elseif ($this->memberType == MemberType::CONTACT) : ?>
		<table>
			<thead class="fixed-thead">
				<tr>
					<th width="40" align="center">Select</th>
					<th width="210">Name</th>
					<th width="200">Account</th>
					<th width="80">City</th>
					<th width="40">State</th>
					<th width="100">Telephone</th>
					<th width="246">Email</th>
				</tr>
			</thead>
			<tbody class="scrollable-tbody">
	<?php if(count($recordSet)) : ?>
		<?php foreach ($recordSet as $contact) : ?>
				<tr>
					<td width="40" align="center">
						<input type="checkbox" id="checkbox_row_<?php echo ++$rowCount; ?>" name="selected_fld[]" value="<?php echo $contact->getId(); ?>">
					</td>
					<td width="210"><?php echo $contact->getDisplayName(true); ?></td>
					<td width="200"><?php echo ($contact->getAccount() ? $contact->getAccount()->getDisplayName(true) : '') ?></td>
					<td width="80"><?php echo $contact->getPrimaryAddress()->getCity(); ?></td>
					<td width="40"><?php echo $contact->getPrimaryAddress()->getRegion(); ?></td>
					<td width="100"><?php echo $contact->getPrimaryTelephone(); ?></td>
					<td width="230"><?php echo $contact->getEmail1(); ?></td>
				</tr>
		<?php endforeach; ?>
	<?php else : ?>
				<tr>
					<td colspan="7" class="no-records">No records found.</td>
				</tr>
	<?php endif; ?>
			</tbody>
		</table>
<?php elseif ($this->memberType == MemberType::LEAD) :  ?>
		<table>
			<thead class="fixed-thead">
				<tr>
					<th width="40" align="center"> Select</th>
					<th width="210">Name</th>
					<th width="140">Address</th>
					<th width="80">City</th>
					<th width="40">State</th>
					<th width="100">Telephone</th>
					<th width="306">Email</th>
				</tr>
			</thead>
			<tbody class="scrollable-tbody">
	<?php if(count($recordSet)) : ?>
		<?php foreach ($recordSet as $lead) : ?>
				<tr>
					<td width="40" align="center">
						<input type="checkbox" id="checkbox_row_<?php echo ++$rowCount; ?>" name="selected_fld[]" value="<?php echo $lead->getId(); ?>">
					</td>
					<td width="210"><?php echo $lead->getDisplayName(true); ?></td>
					<td width="140"><?php echo $lead->getPrimaryAddress()->getShortStreet(); ?></td>
					<td width="80"><?php echo $lead->getPrimaryAddress()->getCity(); ?></td>
					<td width="40"><?php echo $lead->getPrimaryAddress()->getRegion(); ?></td>
					<td width="100"><?php echo $lead->getPrimaryTelephone(); ?></td>
					<td width="290"><?php echo $lead->getEmail1(); ?></td>
				</tr>
		<?php endforeach; ?>
	<?php else : ?>
				<tr>
					<td colspan="7" class="no-records">No records found.</td>
				</tr>
	<?php endif; ?>
			</tbody>
		</table>
<?php endif; ?>
	</div>
	<div class="mtm">
		<div class="lfloat mrm mtt">
			<a id="select-all-add" class="button" href="#">Select All</a>
		</div>
		<input type="submit" class="button" value="Add Selected" name="addSelected">
	</div>
</form>
