<?php

/**
 * Casales Library
 * PHP version 5.4
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * KAATERSKIL MANAGEMENT, LLC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category Casales
 * @package Application
 * @copyright Copyright (c) 2009-2013 Kaaterskil Management, LLC
 * @version SVN $Id: campaignResponseIndex.phtml 13 2013-08-05 22:53:55Z  $
 */
use Application\Model\CampaignResponse;

/* @var $cr CampaignResponse */
?>
<h2>Campaign Responses</h2>
<div class="tabbed-table-container-3">
	<table>
		<thead class="fixed-thead">
			<tr>
				<th width="300" class="first">Subject</th>
				<th width="260">Customer</th>
				<th width="100">Received On</th>
				<th width="120">Response Code</th>
				<th width="133">Status</th>
			</tr>
		</thead>
		<tbody class="scrollable-tbody">
			<?php if(count($this->campaignResponses)) : ?>
			<?php foreach ($this->campaignResponses as $cr) : ?>
			<?php
			$href = $this->url( 'activity', array(
				'action' => 'edit',
				'id' => $cr->getId(),
				'type' => $cr->getDiscriminator(),
				'entityId' => $this->entityId,
				'entityRoute' => $this->entityRoute
			) );
			$link = '<a href="' . $href . '">' . $cr->getSubject() . '</a>';
			?>
			<tr>
				<td width="300" class="first"><?php echo $link; ?></td>
				<td width="260"><?php echo $cr->getRegardingObjectName(true); ?></td>
				<td width="100"><?php echo $cr->getFormattedReceivedOn(); ?></td>
				<td width="120"><?php echo $cr->getResponseCode(); ?></td>
				<td width="117"><?php echo $cr->getStatus(); ?></td>
			</tr>
			<?php endforeach; ?>
			<?php else : ?>
			<tr>
				<td colspan="5" class="tabbed-no-records">No records found.</td>
			</tr>
			<?php endif; ?>
		</tbody>
	</table>
</div>
